// Code generated by ent, DO NOT EDIT.

package storeapp

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the storeapp type in the database.
	Label = "store_app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldReviews holds the string denoting the reviews field in the database.
	FieldReviews = "reviews"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldInstalls holds the string denoting the installs field in the database.
	FieldInstalls = "installs"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldContentRating holds the string denoting the content_rating field in the database.
	FieldContentRating = "content_rating"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// FieldCurrentVer holds the string denoting the current_ver field in the database.
	FieldCurrentVer = "current_ver"
	// FieldInAppPurchases holds the string denoting the in_app_purchases field in the database.
	FieldInAppPurchases = "in_app_purchases"
	// FieldAdSupported holds the string denoting the ad_supported field in the database.
	FieldAdSupported = "ad_supported"
	// EdgeGenres holds the string denoting the genres edge name in mutations.
	EdgeGenres = "genres"
	// EdgeImages holds the string denoting the images edge name in mutations.
	EdgeImages = "images"
	// EdgeUserInstallList holds the string denoting the user_install_list edge name in mutations.
	EdgeUserInstallList = "user_install_list"
	// Table holds the table name of the storeapp in the database.
	Table = "store_apps"
	// GenresTable is the table that holds the genres relation/edge. The primary key declared below.
	GenresTable = "store_app_genres"
	// GenresInverseTable is the table name for the StoreGenre entity.
	// It exists in this package in order to avoid circular dependency with the "storegenre" package.
	GenresInverseTable = "store_genres"
	// ImagesTable is the table that holds the images relation/edge.
	ImagesTable = "images"
	// ImagesInverseTable is the table name for the Image entity.
	// It exists in this package in order to avoid circular dependency with the "image" package.
	ImagesInverseTable = "images"
	// ImagesColumn is the table column denoting the images relation/edge.
	ImagesColumn = "store_app_images"
	// UserInstallListTable is the table that holds the user_install_list relation/edge. The primary key declared below.
	UserInstallListTable = "user_installed_apps"
	// UserInstallListInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInstallListInverseTable = "users"
)

// Columns holds all SQL columns for storeapp fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCategory,
	FieldRating,
	FieldReviews,
	FieldSize,
	FieldInstalls,
	FieldType,
	FieldPrice,
	FieldContentRating,
	FieldLastUpdated,
	FieldCurrentVer,
	FieldInAppPurchases,
	FieldAdSupported,
}

var (
	// GenresPrimaryKey and GenresColumn2 are the table columns denoting the
	// primary key for the genres relation (M2M).
	GenresPrimaryKey = []string{"store_app_id", "store_genre_id"}
	// UserInstallListPrimaryKey and UserInstallListColumn2 are the table columns denoting the
	// primary key for the user_install_list relation (M2M).
	UserInstallListPrimaryKey = []string{"user_id", "store_app_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ReviewsValidator is a validator for the "reviews" field. It is called by the builders before save.
	ReviewsValidator func(int32) error
	// SizeValidator is a validator for the "size" field. It is called by the builders before save.
	SizeValidator func(string) error
	// InstallsValidator is a validator for the "installs" field. It is called by the builders before save.
	InstallsValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float32
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(float32) error
	// ContentRatingValidator is a validator for the "content_rating" field. It is called by the builders before save.
	ContentRatingValidator func(string) error
	// LastUpdatedValidator is a validator for the "last_updated" field. It is called by the builders before save.
	LastUpdatedValidator func(string) error
	// CurrentVerValidator is a validator for the "current_ver" field. It is called by the builders before save.
	CurrentVerValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Category defines the type for the "category" enum field.
type Category string

// Category values.
const (
	CategoryARTIFICIAL_INTELLIGENCE Category = "ARTIFICIAL_INTELLIGENCE"
	CategoryART_AND_DESIGN          Category = "ART_AND_DESIGN"
	CategoryAUTO_AND_VEHICLES       Category = "AUTO_AND_VEHICLES"
	CategoryBEAUTY                  Category = "BEAUTY"
	CategoryBOOKS_AND_REFERENCE     Category = "BOOKS_AND_REFERENCE"
	CategoryBUSINESS                Category = "BUSINESS"
	CategoryCOMICS                  Category = "COMICS"
	CategoryCOMMUNICATION           Category = "COMMUNICATION"
	CategoryDATING                  Category = "DATING"
	CategoryEDUCATION               Category = "EDUCATION"
	CategoryENTERTAINMENT           Category = "ENTERTAINMENT"
	CategoryEVENTS                  Category = "EVENTS"
	CategoryFAMILY                  Category = "FAMILY"
	CategoryFINANCE                 Category = "FINANCE"
	CategoryFOOD_AND_DRINK          Category = "FOOD_AND_DRINK"
	CategoryGAME                    Category = "GAME"
	CategoryHEALTH_AND_FITNESS      Category = "HEALTH_AND_FITNESS"
	CategoryHOUSE_AND_HOME          Category = "HOUSE_AND_HOME"
	CategoryLIBRARIES_AND_DEMO      Category = "LIBRARIES_AND_DEMO"
	CategoryLIFESTYLE               Category = "LIFESTYLE"
	CategoryMAPS_AND_NAVIGATION     Category = "MAPS_AND_NAVIGATION"
	CategoryMEDICAL                 Category = "MEDICAL"
	CategoryNEWS_AND_MAGAZINES      Category = "NEWS_AND_MAGAZINES"
	CategoryPARENTING               Category = "PARENTING"
	CategoryPERSONALIZATION         Category = "PERSONALIZATION"
	CategoryPHOTOGRAPHY             Category = "PHOTOGRAPHY"
	CategoryPRODUCTIVITY            Category = "PRODUCTIVITY"
	CategorySHOPPING                Category = "SHOPPING"
	CategorySOCIAL                  Category = "SOCIAL"
	CategorySPORTS                  Category = "SPORTS"
	CategoryTOOLS                   Category = "TOOLS"
	CategoryTRAVEL_AND_LOCAL        Category = "TRAVEL_AND_LOCAL"
	CategoryVIDEO_PLAYERS           Category = "VIDEO_PLAYERS"
	CategoryVIRTUAL_REALITY         Category = "VIRTUAL_REALITY"
	CategoryWEATHER                 Category = "WEATHER"
	CategoryWEB3_AND_CRYPTO         Category = "WEB3_AND_CRYPTO"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryARTIFICIAL_INTELLIGENCE, CategoryART_AND_DESIGN, CategoryAUTO_AND_VEHICLES, CategoryBEAUTY, CategoryBOOKS_AND_REFERENCE, CategoryBUSINESS, CategoryCOMICS, CategoryCOMMUNICATION, CategoryDATING, CategoryEDUCATION, CategoryENTERTAINMENT, CategoryEVENTS, CategoryFAMILY, CategoryFINANCE, CategoryFOOD_AND_DRINK, CategoryGAME, CategoryHEALTH_AND_FITNESS, CategoryHOUSE_AND_HOME, CategoryLIBRARIES_AND_DEMO, CategoryLIFESTYLE, CategoryMAPS_AND_NAVIGATION, CategoryMEDICAL, CategoryNEWS_AND_MAGAZINES, CategoryPARENTING, CategoryPERSONALIZATION, CategoryPHOTOGRAPHY, CategoryPRODUCTIVITY, CategorySHOPPING, CategorySOCIAL, CategorySPORTS, CategoryTOOLS, CategoryTRAVEL_AND_LOCAL, CategoryVIDEO_PLAYERS, CategoryVIRTUAL_REALITY, CategoryWEATHER, CategoryWEB3_AND_CRYPTO:
		return nil
	default:
		return fmt.Errorf("storeapp: invalid enum value for category field: %q", c)
	}
}

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeFree Type = "Free"
	TypePaid Type = "Paid"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeFree, TypePaid:
		return nil
	default:
		return fmt.Errorf("storeapp: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the StoreApp queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByReviews orders the results by the reviews field.
func ByReviews(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviews, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByInstalls orders the results by the installs field.
func ByInstalls(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalls, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByContentRating orders the results by the content_rating field.
func ByContentRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentRating, opts...).ToFunc()
}

// ByLastUpdated orders the results by the last_updated field.
func ByLastUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdated, opts...).ToFunc()
}

// ByCurrentVer orders the results by the current_ver field.
func ByCurrentVer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentVer, opts...).ToFunc()
}

// ByInAppPurchases orders the results by the in_app_purchases field.
func ByInAppPurchases(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInAppPurchases, opts...).ToFunc()
}

// ByAdSupported orders the results by the ad_supported field.
func ByAdSupported(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdSupported, opts...).ToFunc()
}

// ByGenresCount orders the results by genres count.
func ByGenresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGenresStep(), opts...)
	}
}

// ByGenres orders the results by genres terms.
func ByGenres(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGenresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByImagesCount orders the results by images count.
func ByImagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImagesStep(), opts...)
	}
}

// ByImages orders the results by images terms.
func ByImages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserInstallListCount orders the results by user_install_list count.
func ByUserInstallListCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserInstallListStep(), opts...)
	}
}

// ByUserInstallList orders the results by user_install_list terms.
func ByUserInstallList(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserInstallListStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGenresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GenresInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GenresTable, GenresPrimaryKey...),
	)
}
func newImagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImagesTable, ImagesColumn),
	)
}
func newUserInstallListStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInstallListInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, UserInstallListTable, UserInstallListPrimaryKey...),
	)
}
