// Code generated by ent, DO NOT EDIT.

package storeapp

import (
	"b3_ux_backend/internal/entities/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldName, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldRating, v))
}

// Reviews applies equality check predicate on the "reviews" field. It's identical to ReviewsEQ.
func Reviews(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldReviews, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldSize, v))
}

// Installs applies equality check predicate on the "installs" field. It's identical to InstallsEQ.
func Installs(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldInstalls, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldPrice, v))
}

// ContentRating applies equality check predicate on the "content_rating" field. It's identical to ContentRatingEQ.
func ContentRating(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldContentRating, v))
}

// LastUpdated applies equality check predicate on the "last_updated" field. It's identical to LastUpdatedEQ.
func LastUpdated(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldLastUpdated, v))
}

// CurrentVer applies equality check predicate on the "current_ver" field. It's identical to CurrentVerEQ.
func CurrentVer(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldCurrentVer, v))
}

// InAppPurchases applies equality check predicate on the "in_app_purchases" field. It's identical to InAppPurchasesEQ.
func InAppPurchases(v bool) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldInAppPurchases, v))
}

// AdSupported applies equality check predicate on the "ad_supported" field. It's identical to AdSupportedEQ.
func AdSupported(v bool) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldAdSupported, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContainsFold(FieldName, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v Category) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v Category) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...Category) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...Category) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldCategory, vs...))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldRating, v))
}

// ReviewsEQ applies the EQ predicate on the "reviews" field.
func ReviewsEQ(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldReviews, v))
}

// ReviewsNEQ applies the NEQ predicate on the "reviews" field.
func ReviewsNEQ(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldReviews, v))
}

// ReviewsIn applies the In predicate on the "reviews" field.
func ReviewsIn(vs ...int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldReviews, vs...))
}

// ReviewsNotIn applies the NotIn predicate on the "reviews" field.
func ReviewsNotIn(vs ...int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldReviews, vs...))
}

// ReviewsGT applies the GT predicate on the "reviews" field.
func ReviewsGT(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldReviews, v))
}

// ReviewsGTE applies the GTE predicate on the "reviews" field.
func ReviewsGTE(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldReviews, v))
}

// ReviewsLT applies the LT predicate on the "reviews" field.
func ReviewsLT(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldReviews, v))
}

// ReviewsLTE applies the LTE predicate on the "reviews" field.
func ReviewsLTE(v int32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldReviews, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldSize, v))
}

// SizeContains applies the Contains predicate on the "size" field.
func SizeContains(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContains(FieldSize, v))
}

// SizeHasPrefix applies the HasPrefix predicate on the "size" field.
func SizeHasPrefix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasPrefix(FieldSize, v))
}

// SizeHasSuffix applies the HasSuffix predicate on the "size" field.
func SizeHasSuffix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasSuffix(FieldSize, v))
}

// SizeEqualFold applies the EqualFold predicate on the "size" field.
func SizeEqualFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEqualFold(FieldSize, v))
}

// SizeContainsFold applies the ContainsFold predicate on the "size" field.
func SizeContainsFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContainsFold(FieldSize, v))
}

// InstallsEQ applies the EQ predicate on the "installs" field.
func InstallsEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldInstalls, v))
}

// InstallsNEQ applies the NEQ predicate on the "installs" field.
func InstallsNEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldInstalls, v))
}

// InstallsIn applies the In predicate on the "installs" field.
func InstallsIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldInstalls, vs...))
}

// InstallsNotIn applies the NotIn predicate on the "installs" field.
func InstallsNotIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldInstalls, vs...))
}

// InstallsGT applies the GT predicate on the "installs" field.
func InstallsGT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldInstalls, v))
}

// InstallsGTE applies the GTE predicate on the "installs" field.
func InstallsGTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldInstalls, v))
}

// InstallsLT applies the LT predicate on the "installs" field.
func InstallsLT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldInstalls, v))
}

// InstallsLTE applies the LTE predicate on the "installs" field.
func InstallsLTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldInstalls, v))
}

// InstallsContains applies the Contains predicate on the "installs" field.
func InstallsContains(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContains(FieldInstalls, v))
}

// InstallsHasPrefix applies the HasPrefix predicate on the "installs" field.
func InstallsHasPrefix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasPrefix(FieldInstalls, v))
}

// InstallsHasSuffix applies the HasSuffix predicate on the "installs" field.
func InstallsHasSuffix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasSuffix(FieldInstalls, v))
}

// InstallsEqualFold applies the EqualFold predicate on the "installs" field.
func InstallsEqualFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEqualFold(FieldInstalls, v))
}

// InstallsContainsFold applies the ContainsFold predicate on the "installs" field.
func InstallsContainsFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContainsFold(FieldInstalls, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldType, vs...))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float32) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldPrice, v))
}

// ContentRatingEQ applies the EQ predicate on the "content_rating" field.
func ContentRatingEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldContentRating, v))
}

// ContentRatingNEQ applies the NEQ predicate on the "content_rating" field.
func ContentRatingNEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldContentRating, v))
}

// ContentRatingIn applies the In predicate on the "content_rating" field.
func ContentRatingIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldContentRating, vs...))
}

// ContentRatingNotIn applies the NotIn predicate on the "content_rating" field.
func ContentRatingNotIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldContentRating, vs...))
}

// ContentRatingGT applies the GT predicate on the "content_rating" field.
func ContentRatingGT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldContentRating, v))
}

// ContentRatingGTE applies the GTE predicate on the "content_rating" field.
func ContentRatingGTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldContentRating, v))
}

// ContentRatingLT applies the LT predicate on the "content_rating" field.
func ContentRatingLT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldContentRating, v))
}

// ContentRatingLTE applies the LTE predicate on the "content_rating" field.
func ContentRatingLTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldContentRating, v))
}

// ContentRatingContains applies the Contains predicate on the "content_rating" field.
func ContentRatingContains(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContains(FieldContentRating, v))
}

// ContentRatingHasPrefix applies the HasPrefix predicate on the "content_rating" field.
func ContentRatingHasPrefix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasPrefix(FieldContentRating, v))
}

// ContentRatingHasSuffix applies the HasSuffix predicate on the "content_rating" field.
func ContentRatingHasSuffix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasSuffix(FieldContentRating, v))
}

// ContentRatingEqualFold applies the EqualFold predicate on the "content_rating" field.
func ContentRatingEqualFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEqualFold(FieldContentRating, v))
}

// ContentRatingContainsFold applies the ContainsFold predicate on the "content_rating" field.
func ContentRatingContainsFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContainsFold(FieldContentRating, v))
}

// LastUpdatedEQ applies the EQ predicate on the "last_updated" field.
func LastUpdatedEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldLastUpdated, v))
}

// LastUpdatedNEQ applies the NEQ predicate on the "last_updated" field.
func LastUpdatedNEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldLastUpdated, v))
}

// LastUpdatedIn applies the In predicate on the "last_updated" field.
func LastUpdatedIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldLastUpdated, vs...))
}

// LastUpdatedNotIn applies the NotIn predicate on the "last_updated" field.
func LastUpdatedNotIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldLastUpdated, vs...))
}

// LastUpdatedGT applies the GT predicate on the "last_updated" field.
func LastUpdatedGT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldLastUpdated, v))
}

// LastUpdatedGTE applies the GTE predicate on the "last_updated" field.
func LastUpdatedGTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldLastUpdated, v))
}

// LastUpdatedLT applies the LT predicate on the "last_updated" field.
func LastUpdatedLT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldLastUpdated, v))
}

// LastUpdatedLTE applies the LTE predicate on the "last_updated" field.
func LastUpdatedLTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldLastUpdated, v))
}

// LastUpdatedContains applies the Contains predicate on the "last_updated" field.
func LastUpdatedContains(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContains(FieldLastUpdated, v))
}

// LastUpdatedHasPrefix applies the HasPrefix predicate on the "last_updated" field.
func LastUpdatedHasPrefix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasPrefix(FieldLastUpdated, v))
}

// LastUpdatedHasSuffix applies the HasSuffix predicate on the "last_updated" field.
func LastUpdatedHasSuffix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasSuffix(FieldLastUpdated, v))
}

// LastUpdatedEqualFold applies the EqualFold predicate on the "last_updated" field.
func LastUpdatedEqualFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEqualFold(FieldLastUpdated, v))
}

// LastUpdatedContainsFold applies the ContainsFold predicate on the "last_updated" field.
func LastUpdatedContainsFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContainsFold(FieldLastUpdated, v))
}

// CurrentVerEQ applies the EQ predicate on the "current_ver" field.
func CurrentVerEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldCurrentVer, v))
}

// CurrentVerNEQ applies the NEQ predicate on the "current_ver" field.
func CurrentVerNEQ(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldCurrentVer, v))
}

// CurrentVerIn applies the In predicate on the "current_ver" field.
func CurrentVerIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldIn(FieldCurrentVer, vs...))
}

// CurrentVerNotIn applies the NotIn predicate on the "current_ver" field.
func CurrentVerNotIn(vs ...string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNotIn(FieldCurrentVer, vs...))
}

// CurrentVerGT applies the GT predicate on the "current_ver" field.
func CurrentVerGT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGT(FieldCurrentVer, v))
}

// CurrentVerGTE applies the GTE predicate on the "current_ver" field.
func CurrentVerGTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldGTE(FieldCurrentVer, v))
}

// CurrentVerLT applies the LT predicate on the "current_ver" field.
func CurrentVerLT(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLT(FieldCurrentVer, v))
}

// CurrentVerLTE applies the LTE predicate on the "current_ver" field.
func CurrentVerLTE(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldLTE(FieldCurrentVer, v))
}

// CurrentVerContains applies the Contains predicate on the "current_ver" field.
func CurrentVerContains(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContains(FieldCurrentVer, v))
}

// CurrentVerHasPrefix applies the HasPrefix predicate on the "current_ver" field.
func CurrentVerHasPrefix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasPrefix(FieldCurrentVer, v))
}

// CurrentVerHasSuffix applies the HasSuffix predicate on the "current_ver" field.
func CurrentVerHasSuffix(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldHasSuffix(FieldCurrentVer, v))
}

// CurrentVerEqualFold applies the EqualFold predicate on the "current_ver" field.
func CurrentVerEqualFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEqualFold(FieldCurrentVer, v))
}

// CurrentVerContainsFold applies the ContainsFold predicate on the "current_ver" field.
func CurrentVerContainsFold(v string) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldContainsFold(FieldCurrentVer, v))
}

// InAppPurchasesEQ applies the EQ predicate on the "in_app_purchases" field.
func InAppPurchasesEQ(v bool) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldInAppPurchases, v))
}

// InAppPurchasesNEQ applies the NEQ predicate on the "in_app_purchases" field.
func InAppPurchasesNEQ(v bool) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldInAppPurchases, v))
}

// AdSupportedEQ applies the EQ predicate on the "ad_supported" field.
func AdSupportedEQ(v bool) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldEQ(FieldAdSupported, v))
}

// AdSupportedNEQ applies the NEQ predicate on the "ad_supported" field.
func AdSupportedNEQ(v bool) predicate.StoreApp {
	return predicate.StoreApp(sql.FieldNEQ(FieldAdSupported, v))
}

// HasGenres applies the HasEdge predicate on the "genres" edge.
func HasGenres() predicate.StoreApp {
	return predicate.StoreApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GenresTable, GenresPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenresWith applies the HasEdge predicate on the "genres" edge with a given conditions (other predicates).
func HasGenresWith(preds ...predicate.StoreGenre) predicate.StoreApp {
	return predicate.StoreApp(func(s *sql.Selector) {
		step := newGenresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasImages applies the HasEdge predicate on the "images" edge.
func HasImages() predicate.StoreApp {
	return predicate.StoreApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ImagesTable, ImagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImagesWith applies the HasEdge predicate on the "images" edge with a given conditions (other predicates).
func HasImagesWith(preds ...predicate.Image) predicate.StoreApp {
	return predicate.StoreApp(func(s *sql.Selector) {
		step := newImagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserInstallList applies the HasEdge predicate on the "user_install_list" edge.
func HasUserInstallList() predicate.StoreApp {
	return predicate.StoreApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UserInstallListTable, UserInstallListPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserInstallListWith applies the HasEdge predicate on the "user_install_list" edge with a given conditions (other predicates).
func HasUserInstallListWith(preds ...predicate.User) predicate.StoreApp {
	return predicate.StoreApp(func(s *sql.Selector) {
		step := newUserInstallListStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StoreApp) predicate.StoreApp {
	return predicate.StoreApp(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StoreApp) predicate.StoreApp {
	return predicate.StoreApp(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StoreApp) predicate.StoreApp {
	return predicate.StoreApp(sql.NotPredicates(p))
}
