// Code generated by ent, DO NOT EDIT.

package entities

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"b3_ux_backend/internal/entities/migrate"

	"b3_ux_backend/internal/entities/storeapp"
	"b3_ux_backend/internal/entities/storegenre"
	"b3_ux_backend/internal/entities/wywwgenre"
	"b3_ux_backend/internal/entities/wywwmovie"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// StoreApp is the client for interacting with the StoreApp builders.
	StoreApp *StoreAppClient
	// StoreGenre is the client for interacting with the StoreGenre builders.
	StoreGenre *StoreGenreClient
	// WywwGenre is the client for interacting with the WywwGenre builders.
	WywwGenre *WywwGenreClient
	// WywwMovie is the client for interacting with the WywwMovie builders.
	WywwMovie *WywwMovieClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.StoreApp = NewStoreAppClient(c.config)
	c.StoreGenre = NewStoreGenreClient(c.config)
	c.WywwGenre = NewWywwGenreClient(c.config)
	c.WywwMovie = NewWywwMovieClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entities: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entities: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		StoreApp:   NewStoreAppClient(cfg),
		StoreGenre: NewStoreGenreClient(cfg),
		WywwGenre:  NewWywwGenreClient(cfg),
		WywwMovie:  NewWywwMovieClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		StoreApp:   NewStoreAppClient(cfg),
		StoreGenre: NewStoreGenreClient(cfg),
		WywwGenre:  NewWywwGenreClient(cfg),
		WywwMovie:  NewWywwMovieClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		StoreApp.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.StoreApp.Use(hooks...)
	c.StoreGenre.Use(hooks...)
	c.WywwGenre.Use(hooks...)
	c.WywwMovie.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.StoreApp.Intercept(interceptors...)
	c.StoreGenre.Intercept(interceptors...)
	c.WywwGenre.Intercept(interceptors...)
	c.WywwMovie.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *StoreAppMutation:
		return c.StoreApp.mutate(ctx, m)
	case *StoreGenreMutation:
		return c.StoreGenre.mutate(ctx, m)
	case *WywwGenreMutation:
		return c.WywwGenre.mutate(ctx, m)
	case *WywwMovieMutation:
		return c.WywwMovie.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entities: unknown mutation type %T", m)
	}
}

// StoreAppClient is a client for the StoreApp schema.
type StoreAppClient struct {
	config
}

// NewStoreAppClient returns a client for the StoreApp from the given config.
func NewStoreAppClient(c config) *StoreAppClient {
	return &StoreAppClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `storeapp.Hooks(f(g(h())))`.
func (c *StoreAppClient) Use(hooks ...Hook) {
	c.hooks.StoreApp = append(c.hooks.StoreApp, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `storeapp.Intercept(f(g(h())))`.
func (c *StoreAppClient) Intercept(interceptors ...Interceptor) {
	c.inters.StoreApp = append(c.inters.StoreApp, interceptors...)
}

// Create returns a builder for creating a StoreApp entity.
func (c *StoreAppClient) Create() *StoreAppCreate {
	mutation := newStoreAppMutation(c.config, OpCreate)
	return &StoreAppCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StoreApp entities.
func (c *StoreAppClient) CreateBulk(builders ...*StoreAppCreate) *StoreAppCreateBulk {
	return &StoreAppCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StoreAppClient) MapCreateBulk(slice any, setFunc func(*StoreAppCreate, int)) *StoreAppCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StoreAppCreateBulk{err: fmt.Errorf("calling to StoreAppClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StoreAppCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StoreAppCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StoreApp.
func (c *StoreAppClient) Update() *StoreAppUpdate {
	mutation := newStoreAppMutation(c.config, OpUpdate)
	return &StoreAppUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StoreAppClient) UpdateOne(_m *StoreApp) *StoreAppUpdateOne {
	mutation := newStoreAppMutation(c.config, OpUpdateOne, withStoreApp(_m))
	return &StoreAppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StoreAppClient) UpdateOneID(id uuid.UUID) *StoreAppUpdateOne {
	mutation := newStoreAppMutation(c.config, OpUpdateOne, withStoreAppID(id))
	return &StoreAppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StoreApp.
func (c *StoreAppClient) Delete() *StoreAppDelete {
	mutation := newStoreAppMutation(c.config, OpDelete)
	return &StoreAppDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StoreAppClient) DeleteOne(_m *StoreApp) *StoreAppDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StoreAppClient) DeleteOneID(id uuid.UUID) *StoreAppDeleteOne {
	builder := c.Delete().Where(storeapp.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StoreAppDeleteOne{builder}
}

// Query returns a query builder for StoreApp.
func (c *StoreAppClient) Query() *StoreAppQuery {
	return &StoreAppQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStoreApp},
		inters: c.Interceptors(),
	}
}

// Get returns a StoreApp entity by its id.
func (c *StoreAppClient) Get(ctx context.Context, id uuid.UUID) (*StoreApp, error) {
	return c.Query().Where(storeapp.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StoreAppClient) GetX(ctx context.Context, id uuid.UUID) *StoreApp {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGenres queries the genres edge of a StoreApp.
func (c *StoreAppClient) QueryGenres(_m *StoreApp) *StoreGenreQuery {
	query := (&StoreGenreClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(storeapp.Table, storeapp.FieldID, id),
			sqlgraph.To(storegenre.Table, storegenre.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, storeapp.GenresTable, storeapp.GenresPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StoreAppClient) Hooks() []Hook {
	return c.hooks.StoreApp
}

// Interceptors returns the client interceptors.
func (c *StoreAppClient) Interceptors() []Interceptor {
	return c.inters.StoreApp
}

func (c *StoreAppClient) mutate(ctx context.Context, m *StoreAppMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StoreAppCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StoreAppUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StoreAppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StoreAppDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entities: unknown StoreApp mutation op: %q", m.Op())
	}
}

// StoreGenreClient is a client for the StoreGenre schema.
type StoreGenreClient struct {
	config
}

// NewStoreGenreClient returns a client for the StoreGenre from the given config.
func NewStoreGenreClient(c config) *StoreGenreClient {
	return &StoreGenreClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `storegenre.Hooks(f(g(h())))`.
func (c *StoreGenreClient) Use(hooks ...Hook) {
	c.hooks.StoreGenre = append(c.hooks.StoreGenre, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `storegenre.Intercept(f(g(h())))`.
func (c *StoreGenreClient) Intercept(interceptors ...Interceptor) {
	c.inters.StoreGenre = append(c.inters.StoreGenre, interceptors...)
}

// Create returns a builder for creating a StoreGenre entity.
func (c *StoreGenreClient) Create() *StoreGenreCreate {
	mutation := newStoreGenreMutation(c.config, OpCreate)
	return &StoreGenreCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StoreGenre entities.
func (c *StoreGenreClient) CreateBulk(builders ...*StoreGenreCreate) *StoreGenreCreateBulk {
	return &StoreGenreCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StoreGenreClient) MapCreateBulk(slice any, setFunc func(*StoreGenreCreate, int)) *StoreGenreCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StoreGenreCreateBulk{err: fmt.Errorf("calling to StoreGenreClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StoreGenreCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StoreGenreCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StoreGenre.
func (c *StoreGenreClient) Update() *StoreGenreUpdate {
	mutation := newStoreGenreMutation(c.config, OpUpdate)
	return &StoreGenreUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StoreGenreClient) UpdateOne(_m *StoreGenre) *StoreGenreUpdateOne {
	mutation := newStoreGenreMutation(c.config, OpUpdateOne, withStoreGenre(_m))
	return &StoreGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StoreGenreClient) UpdateOneID(id uuid.UUID) *StoreGenreUpdateOne {
	mutation := newStoreGenreMutation(c.config, OpUpdateOne, withStoreGenreID(id))
	return &StoreGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StoreGenre.
func (c *StoreGenreClient) Delete() *StoreGenreDelete {
	mutation := newStoreGenreMutation(c.config, OpDelete)
	return &StoreGenreDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StoreGenreClient) DeleteOne(_m *StoreGenre) *StoreGenreDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StoreGenreClient) DeleteOneID(id uuid.UUID) *StoreGenreDeleteOne {
	builder := c.Delete().Where(storegenre.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StoreGenreDeleteOne{builder}
}

// Query returns a query builder for StoreGenre.
func (c *StoreGenreClient) Query() *StoreGenreQuery {
	return &StoreGenreQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStoreGenre},
		inters: c.Interceptors(),
	}
}

// Get returns a StoreGenre entity by its id.
func (c *StoreGenreClient) Get(ctx context.Context, id uuid.UUID) (*StoreGenre, error) {
	return c.Query().Where(storegenre.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StoreGenreClient) GetX(ctx context.Context, id uuid.UUID) *StoreGenre {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryApp queries the app edge of a StoreGenre.
func (c *StoreGenreClient) QueryApp(_m *StoreGenre) *StoreAppQuery {
	query := (&StoreAppClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(storegenre.Table, storegenre.FieldID, id),
			sqlgraph.To(storeapp.Table, storeapp.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, storegenre.AppTable, storegenre.AppPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StoreGenreClient) Hooks() []Hook {
	return c.hooks.StoreGenre
}

// Interceptors returns the client interceptors.
func (c *StoreGenreClient) Interceptors() []Interceptor {
	return c.inters.StoreGenre
}

func (c *StoreGenreClient) mutate(ctx context.Context, m *StoreGenreMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StoreGenreCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StoreGenreUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StoreGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StoreGenreDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entities: unknown StoreGenre mutation op: %q", m.Op())
	}
}

// WywwGenreClient is a client for the WywwGenre schema.
type WywwGenreClient struct {
	config
}

// NewWywwGenreClient returns a client for the WywwGenre from the given config.
func NewWywwGenreClient(c config) *WywwGenreClient {
	return &WywwGenreClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wywwgenre.Hooks(f(g(h())))`.
func (c *WywwGenreClient) Use(hooks ...Hook) {
	c.hooks.WywwGenre = append(c.hooks.WywwGenre, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wywwgenre.Intercept(f(g(h())))`.
func (c *WywwGenreClient) Intercept(interceptors ...Interceptor) {
	c.inters.WywwGenre = append(c.inters.WywwGenre, interceptors...)
}

// Create returns a builder for creating a WywwGenre entity.
func (c *WywwGenreClient) Create() *WywwGenreCreate {
	mutation := newWywwGenreMutation(c.config, OpCreate)
	return &WywwGenreCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WywwGenre entities.
func (c *WywwGenreClient) CreateBulk(builders ...*WywwGenreCreate) *WywwGenreCreateBulk {
	return &WywwGenreCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WywwGenreClient) MapCreateBulk(slice any, setFunc func(*WywwGenreCreate, int)) *WywwGenreCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WywwGenreCreateBulk{err: fmt.Errorf("calling to WywwGenreClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WywwGenreCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WywwGenreCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WywwGenre.
func (c *WywwGenreClient) Update() *WywwGenreUpdate {
	mutation := newWywwGenreMutation(c.config, OpUpdate)
	return &WywwGenreUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WywwGenreClient) UpdateOne(_m *WywwGenre) *WywwGenreUpdateOne {
	mutation := newWywwGenreMutation(c.config, OpUpdateOne, withWywwGenre(_m))
	return &WywwGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WywwGenreClient) UpdateOneID(id uuid.UUID) *WywwGenreUpdateOne {
	mutation := newWywwGenreMutation(c.config, OpUpdateOne, withWywwGenreID(id))
	return &WywwGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WywwGenre.
func (c *WywwGenreClient) Delete() *WywwGenreDelete {
	mutation := newWywwGenreMutation(c.config, OpDelete)
	return &WywwGenreDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WywwGenreClient) DeleteOne(_m *WywwGenre) *WywwGenreDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WywwGenreClient) DeleteOneID(id uuid.UUID) *WywwGenreDeleteOne {
	builder := c.Delete().Where(wywwgenre.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WywwGenreDeleteOne{builder}
}

// Query returns a query builder for WywwGenre.
func (c *WywwGenreClient) Query() *WywwGenreQuery {
	return &WywwGenreQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWywwGenre},
		inters: c.Interceptors(),
	}
}

// Get returns a WywwGenre entity by its id.
func (c *WywwGenreClient) Get(ctx context.Context, id uuid.UUID) (*WywwGenre, error) {
	return c.Query().Where(wywwgenre.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WywwGenreClient) GetX(ctx context.Context, id uuid.UUID) *WywwGenre {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryApp queries the app edge of a WywwGenre.
func (c *WywwGenreClient) QueryApp(_m *WywwGenre) *WywwMovieQuery {
	query := (&WywwMovieClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(wywwgenre.Table, wywwgenre.FieldID, id),
			sqlgraph.To(wywwmovie.Table, wywwmovie.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, wywwgenre.AppTable, wywwgenre.AppPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WywwGenreClient) Hooks() []Hook {
	return c.hooks.WywwGenre
}

// Interceptors returns the client interceptors.
func (c *WywwGenreClient) Interceptors() []Interceptor {
	return c.inters.WywwGenre
}

func (c *WywwGenreClient) mutate(ctx context.Context, m *WywwGenreMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WywwGenreCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WywwGenreUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WywwGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WywwGenreDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entities: unknown WywwGenre mutation op: %q", m.Op())
	}
}

// WywwMovieClient is a client for the WywwMovie schema.
type WywwMovieClient struct {
	config
}

// NewWywwMovieClient returns a client for the WywwMovie from the given config.
func NewWywwMovieClient(c config) *WywwMovieClient {
	return &WywwMovieClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wywwmovie.Hooks(f(g(h())))`.
func (c *WywwMovieClient) Use(hooks ...Hook) {
	c.hooks.WywwMovie = append(c.hooks.WywwMovie, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wywwmovie.Intercept(f(g(h())))`.
func (c *WywwMovieClient) Intercept(interceptors ...Interceptor) {
	c.inters.WywwMovie = append(c.inters.WywwMovie, interceptors...)
}

// Create returns a builder for creating a WywwMovie entity.
func (c *WywwMovieClient) Create() *WywwMovieCreate {
	mutation := newWywwMovieMutation(c.config, OpCreate)
	return &WywwMovieCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WywwMovie entities.
func (c *WywwMovieClient) CreateBulk(builders ...*WywwMovieCreate) *WywwMovieCreateBulk {
	return &WywwMovieCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WywwMovieClient) MapCreateBulk(slice any, setFunc func(*WywwMovieCreate, int)) *WywwMovieCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WywwMovieCreateBulk{err: fmt.Errorf("calling to WywwMovieClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WywwMovieCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WywwMovieCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WywwMovie.
func (c *WywwMovieClient) Update() *WywwMovieUpdate {
	mutation := newWywwMovieMutation(c.config, OpUpdate)
	return &WywwMovieUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WywwMovieClient) UpdateOne(_m *WywwMovie) *WywwMovieUpdateOne {
	mutation := newWywwMovieMutation(c.config, OpUpdateOne, withWywwMovie(_m))
	return &WywwMovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WywwMovieClient) UpdateOneID(id uuid.UUID) *WywwMovieUpdateOne {
	mutation := newWywwMovieMutation(c.config, OpUpdateOne, withWywwMovieID(id))
	return &WywwMovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WywwMovie.
func (c *WywwMovieClient) Delete() *WywwMovieDelete {
	mutation := newWywwMovieMutation(c.config, OpDelete)
	return &WywwMovieDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WywwMovieClient) DeleteOne(_m *WywwMovie) *WywwMovieDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WywwMovieClient) DeleteOneID(id uuid.UUID) *WywwMovieDeleteOne {
	builder := c.Delete().Where(wywwmovie.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WywwMovieDeleteOne{builder}
}

// Query returns a query builder for WywwMovie.
func (c *WywwMovieClient) Query() *WywwMovieQuery {
	return &WywwMovieQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWywwMovie},
		inters: c.Interceptors(),
	}
}

// Get returns a WywwMovie entity by its id.
func (c *WywwMovieClient) Get(ctx context.Context, id uuid.UUID) (*WywwMovie, error) {
	return c.Query().Where(wywwmovie.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WywwMovieClient) GetX(ctx context.Context, id uuid.UUID) *WywwMovie {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGenres queries the genres edge of a WywwMovie.
func (c *WywwMovieClient) QueryGenres(_m *WywwMovie) *WywwGenreQuery {
	query := (&WywwGenreClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(wywwmovie.Table, wywwmovie.FieldID, id),
			sqlgraph.To(wywwgenre.Table, wywwgenre.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, wywwmovie.GenresTable, wywwmovie.GenresPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WywwMovieClient) Hooks() []Hook {
	return c.hooks.WywwMovie
}

// Interceptors returns the client interceptors.
func (c *WywwMovieClient) Interceptors() []Interceptor {
	return c.inters.WywwMovie
}

func (c *WywwMovieClient) mutate(ctx context.Context, m *WywwMovieMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WywwMovieCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WywwMovieUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WywwMovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WywwMovieDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entities: unknown WywwMovie mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		StoreApp, StoreGenre, WywwGenre, WywwMovie []ent.Hook
	}
	inters struct {
		StoreApp, StoreGenre, WywwGenre, WywwMovie []ent.Interceptor
	}
)
