// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/color"
	"b3_ux_backend/internal/entities/image"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ColorCreate is the builder for creating a Color entity.
type ColorCreate struct {
	config
	mutation *ColorMutation
	hooks    []Hook
}

// SetR sets the "r" field.
func (_c *ColorCreate) SetR(v int) *ColorCreate {
	_c.mutation.SetR(v)
	return _c
}

// SetG sets the "g" field.
func (_c *ColorCreate) SetG(v int) *ColorCreate {
	_c.mutation.SetG(v)
	return _c
}

// SetB sets the "b" field.
func (_c *ColorCreate) SetB(v int) *ColorCreate {
	_c.mutation.SetB(v)
	return _c
}

// SetRatio sets the "ratio" field.
func (_c *ColorCreate) SetRatio(v float32) *ColorCreate {
	_c.mutation.SetRatio(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ColorCreate) SetID(v uuid.UUID) *ColorCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ColorCreate) SetNillableID(v *uuid.UUID) *ColorCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetImageID sets the "image" edge to the Image entity by ID.
func (_c *ColorCreate) SetImageID(id uuid.UUID) *ColorCreate {
	_c.mutation.SetImageID(id)
	return _c
}

// SetNillableImageID sets the "image" edge to the Image entity by ID if the given value is not nil.
func (_c *ColorCreate) SetNillableImageID(id *uuid.UUID) *ColorCreate {
	if id != nil {
		_c = _c.SetImageID(*id)
	}
	return _c
}

// SetImage sets the "image" edge to the Image entity.
func (_c *ColorCreate) SetImage(v *Image) *ColorCreate {
	return _c.SetImageID(v.ID)
}

// Mutation returns the ColorMutation object of the builder.
func (_c *ColorCreate) Mutation() *ColorMutation {
	return _c.mutation
}

// Save creates the Color in the database.
func (_c *ColorCreate) Save(ctx context.Context) (*Color, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ColorCreate) SaveX(ctx context.Context) *Color {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ColorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ColorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ColorCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := color.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ColorCreate) check() error {
	if _, ok := _c.mutation.R(); !ok {
		return &ValidationError{Name: "r", err: errors.New(`entities: missing required field "Color.r"`)}
	}
	if v, ok := _c.mutation.R(); ok {
		if err := color.RValidator(v); err != nil {
			return &ValidationError{Name: "r", err: fmt.Errorf(`entities: validator failed for field "Color.r": %w`, err)}
		}
	}
	if _, ok := _c.mutation.G(); !ok {
		return &ValidationError{Name: "g", err: errors.New(`entities: missing required field "Color.g"`)}
	}
	if v, ok := _c.mutation.G(); ok {
		if err := color.GValidator(v); err != nil {
			return &ValidationError{Name: "g", err: fmt.Errorf(`entities: validator failed for field "Color.g": %w`, err)}
		}
	}
	if _, ok := _c.mutation.B(); !ok {
		return &ValidationError{Name: "b", err: errors.New(`entities: missing required field "Color.b"`)}
	}
	if v, ok := _c.mutation.B(); ok {
		if err := color.BValidator(v); err != nil {
			return &ValidationError{Name: "b", err: fmt.Errorf(`entities: validator failed for field "Color.b": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ratio(); !ok {
		return &ValidationError{Name: "ratio", err: errors.New(`entities: missing required field "Color.ratio"`)}
	}
	if v, ok := _c.mutation.Ratio(); ok {
		if err := color.RatioValidator(v); err != nil {
			return &ValidationError{Name: "ratio", err: fmt.Errorf(`entities: validator failed for field "Color.ratio": %w`, err)}
		}
	}
	return nil
}

func (_c *ColorCreate) sqlSave(ctx context.Context) (*Color, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ColorCreate) createSpec() (*Color, *sqlgraph.CreateSpec) {
	var (
		_node = &Color{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(color.Table, sqlgraph.NewFieldSpec(color.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.R(); ok {
		_spec.SetField(color.FieldR, field.TypeInt, value)
		_node.R = value
	}
	if value, ok := _c.mutation.G(); ok {
		_spec.SetField(color.FieldG, field.TypeInt, value)
		_node.G = value
	}
	if value, ok := _c.mutation.B(); ok {
		_spec.SetField(color.FieldB, field.TypeInt, value)
		_node.B = value
	}
	if value, ok := _c.mutation.Ratio(); ok {
		_spec.SetField(color.FieldRatio, field.TypeFloat32, value)
		_node.Ratio = value
	}
	if nodes := _c.mutation.ImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   color.ImageTable,
			Columns: []string{color.ImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_colors = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ColorCreateBulk is the builder for creating many Color entities in bulk.
type ColorCreateBulk struct {
	config
	err      error
	builders []*ColorCreate
}

// Save creates the Color entities in the database.
func (_c *ColorCreateBulk) Save(ctx context.Context) ([]*Color, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Color, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ColorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ColorCreateBulk) SaveX(ctx context.Context) []*Color {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ColorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ColorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
