// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/storeapp"
	"b3_ux_backend/internal/entities/wywwmovie"

	"github.com/google/uuid"
)

type StoreAppData struct {
	ID uuid.UUID `json:"id"`

	Name string `json:"name"`

	Category storeapp.Category `json:"category"`

	Rating *float32 `json:"rating"`

	Reviews int32 `json:"reviews"`

	Size string `json:"size"`

	Installs string `json:"installs"`

	Type storeapp.Type `json:"type"`

	Price float32 `json:"price"`

	ContentRating string `json:"content_rating"`

	LastUpdated string `json:"last_updated"`

	CurrentVer string `json:"current_ver"`

	InAppPurchases bool `json:"in_app_purchases"`

	AdSupported bool `json:"ad_supported"`

	Genres []StoreGenreData `json:"genres"`
}

func (n *StoreApp) ToData() *StoreAppData {
	result := StoreAppData{
		ID: n.ID,

		Name: n.Name,

		Category: n.Category,

		Rating: n.Rating,

		Reviews: n.Reviews,

		Size: n.Size,

		Installs: n.Installs,

		Type: n.Type,

		Price: n.Price,

		ContentRating: n.ContentRating,

		LastUpdated: n.LastUpdated,

		CurrentVer: n.CurrentVer,

		InAppPurchases: n.InAppPurchases,

		AdSupported: n.AdSupported,
	}

	if n.Edges.Genres != nil {

		for _, i := range n.Edges.Genres {
			result.Genres = append(result.Genres, *i.ToData())
		}

	}

	return &result
}

type StoreGenreData struct {
	ID uuid.UUID `json:"id"`

	Name string `json:"name"`

	App []StoreAppData `json:"app"`
}

func (n *StoreGenre) ToData() *StoreGenreData {
	result := StoreGenreData{
		ID: n.ID,

		Name: n.Name,
	}

	if n.Edges.App != nil {

		for _, i := range n.Edges.App {
			result.App = append(result.App, *i.ToData())
		}

	}

	return &result
}

type WywwGenreData struct {
	ID uuid.UUID `json:"id"`

	Name string `json:"name"`

	App []WywwMovieData `json:"app"`
}

func (n *WywwGenre) ToData() *WywwGenreData {
	result := WywwGenreData{
		ID: n.ID,

		Name: n.Name,
	}

	if n.Edges.App != nil {

		for _, i := range n.Edges.App {
			result.App = append(result.App, *i.ToData())
		}

	}

	return &result
}

type WywwMovieData struct {
	ID uuid.UUID `json:"id"`

	MovieTitle string `json:"movie_title"`

	OriginalTitle string `json:"original_title"`

	ContentRating wywwmovie.ContentRating `json:"content_rating"`

	Description string `json:"description"`

	PosterPath *string `json:"poster_path"`

	BannerPath *string `json:"banner_path"`

	ReleasedYear int32 `json:"released_year"`

	Runtime int32 `json:"runtime"`

	Rating float32 `json:"rating"`

	Genres []WywwGenreData `json:"genres"`
}

func (n *WywwMovie) ToData() *WywwMovieData {
	result := WywwMovieData{
		ID: n.ID,

		MovieTitle: n.MovieTitle,

		OriginalTitle: n.OriginalTitle,

		ContentRating: n.ContentRating,

		Description: n.Description,

		PosterPath: n.PosterPath,

		BannerPath: n.BannerPath,

		ReleasedYear: n.ReleasedYear,

		Runtime: n.Runtime,

		Rating: n.Rating,
	}

	if n.Edges.Genres != nil {

		for _, i := range n.Edges.Genres {
			result.Genres = append(result.Genres, *i.ToData())
		}

	}

	return &result
}
