// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/color"
	"b3_ux_backend/internal/entities/image"
	"b3_ux_backend/internal/entities/storeapp"
	"b3_ux_backend/internal/entities/wywwmovie"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ImageCreate is the builder for creating a Image entity.
type ImageCreate struct {
	config
	mutation *ImageMutation
	hooks    []Hook
}

// SetFilename sets the "filename" field.
func (_c *ImageCreate) SetFilename(v string) *ImageCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *ImageCreate) SetPath(v string) *ImageCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageCreate) SetWidth(v int) *ImageCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageCreate) SetHeight(v int) *ImageCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ImageCreate) SetKind(v image.Kind) *ImageCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ImageCreate) SetID(v uuid.UUID) *ImageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ImageCreate) SetNillableID(v *uuid.UUID) *ImageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddColorIDs adds the "colors" edge to the Color entity by IDs.
func (_c *ImageCreate) AddColorIDs(ids ...uuid.UUID) *ImageCreate {
	_c.mutation.AddColorIDs(ids...)
	return _c
}

// AddColors adds the "colors" edges to the Color entity.
func (_c *ImageCreate) AddColors(v ...*Color) *ImageCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddColorIDs(ids...)
}

// SetMovieID sets the "movie" edge to the WywwMovie entity by ID.
func (_c *ImageCreate) SetMovieID(id uuid.UUID) *ImageCreate {
	_c.mutation.SetMovieID(id)
	return _c
}

// SetNillableMovieID sets the "movie" edge to the WywwMovie entity by ID if the given value is not nil.
func (_c *ImageCreate) SetNillableMovieID(id *uuid.UUID) *ImageCreate {
	if id != nil {
		_c = _c.SetMovieID(*id)
	}
	return _c
}

// SetMovie sets the "movie" edge to the WywwMovie entity.
func (_c *ImageCreate) SetMovie(v *WywwMovie) *ImageCreate {
	return _c.SetMovieID(v.ID)
}

// SetStoreID sets the "store" edge to the StoreApp entity by ID.
func (_c *ImageCreate) SetStoreID(id uuid.UUID) *ImageCreate {
	_c.mutation.SetStoreID(id)
	return _c
}

// SetNillableStoreID sets the "store" edge to the StoreApp entity by ID if the given value is not nil.
func (_c *ImageCreate) SetNillableStoreID(id *uuid.UUID) *ImageCreate {
	if id != nil {
		_c = _c.SetStoreID(*id)
	}
	return _c
}

// SetStore sets the "store" edge to the StoreApp entity.
func (_c *ImageCreate) SetStore(v *StoreApp) *ImageCreate {
	return _c.SetStoreID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_c *ImageCreate) Mutation() *ImageMutation {
	return _c.mutation
}

// Save creates the Image in the database.
func (_c *ImageCreate) Save(ctx context.Context) (*Image, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageCreate) SaveX(ctx context.Context) *Image {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := image.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageCreate) check() error {
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`entities: missing required field "Image.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := image.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`entities: validator failed for field "Image.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`entities: missing required field "Image.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := image.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`entities: validator failed for field "Image.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`entities: missing required field "Image.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := image.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`entities: validator failed for field "Image.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`entities: missing required field "Image.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := image.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`entities: validator failed for field "Image.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`entities: missing required field "Image.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := image.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`entities: validator failed for field "Image.kind": %w`, err)}
		}
	}
	return nil
}

func (_c *ImageCreate) sqlSave(ctx context.Context) (*Image, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageCreate) createSpec() (*Image, *sqlgraph.CreateSpec) {
	var (
		_node = &Image{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(image.Table, sqlgraph.NewFieldSpec(image.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(image.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(image.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(image.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if nodes := _c.mutation.ColorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   image.ColorsTable,
			Columns: []string{image.ColorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(color.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.MovieTable,
			Columns: []string{image.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.wyww_movie_images = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.StoreTable,
			Columns: []string{image.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storeapp.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.store_app_images = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ImageCreateBulk is the builder for creating many Image entities in bulk.
type ImageCreateBulk struct {
	config
	err      error
	builders []*ImageCreate
}

// Save creates the Image entities in the database.
func (_c *ImageCreateBulk) Save(ctx context.Context) ([]*Image, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Image, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageCreateBulk) SaveX(ctx context.Context) []*Image {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
