// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/predicate"
	"b3_ux_backend/internal/entities/storeapp"
	"b3_ux_backend/internal/entities/storegenre"
	"b3_ux_backend/internal/entities/wywwgenre"
	"b3_ux_backend/internal/entities/wywwmovie"
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeStoreApp   = "StoreApp"
	TypeStoreGenre = "StoreGenre"
	TypeWywwGenre  = "WywwGenre"
	TypeWywwMovie  = "WywwMovie"
)

// StoreAppMutation represents an operation that mutates the StoreApp nodes in the graph.
type StoreAppMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	name             *string
	category         *storeapp.Category
	rating           *float32
	addrating        *float32
	reviews          *int32
	addreviews       *int32
	size             *string
	installs         *string
	_type            *storeapp.Type
	price            *float32
	addprice         *float32
	content_rating   *string
	last_updated     *string
	current_ver      *string
	in_app_purchases *bool
	ad_supported     *bool
	clearedFields    map[string]struct{}
	genres           map[uuid.UUID]struct{}
	removedgenres    map[uuid.UUID]struct{}
	clearedgenres    bool
	done             bool
	oldValue         func(context.Context) (*StoreApp, error)
	predicates       []predicate.StoreApp
}

var _ ent.Mutation = (*StoreAppMutation)(nil)

// storeappOption allows management of the mutation configuration using functional options.
type storeappOption func(*StoreAppMutation)

// newStoreAppMutation creates new mutation for the StoreApp entity.
func newStoreAppMutation(c config, op Op, opts ...storeappOption) *StoreAppMutation {
	m := &StoreAppMutation{
		config:        c,
		op:            op,
		typ:           TypeStoreApp,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStoreAppID sets the ID field of the mutation.
func withStoreAppID(id uuid.UUID) storeappOption {
	return func(m *StoreAppMutation) {
		var (
			err   error
			once  sync.Once
			value *StoreApp
		)
		m.oldValue = func(ctx context.Context) (*StoreApp, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StoreApp.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStoreApp sets the old StoreApp of the mutation.
func withStoreApp(node *StoreApp) storeappOption {
	return func(m *StoreAppMutation) {
		m.oldValue = func(context.Context) (*StoreApp, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StoreAppMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StoreAppMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entities: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of StoreApp entities.
func (m *StoreAppMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StoreAppMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StoreAppMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().StoreApp.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *StoreAppMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *StoreAppMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *StoreAppMutation) ResetName() {
	m.name = nil
}

// SetCategory sets the "category" field.
func (m *StoreAppMutation) SetCategory(s storeapp.Category) {
	m.category = &s
}

// Category returns the value of the "category" field in the mutation.
func (m *StoreAppMutation) Category() (r storeapp.Category, exists bool) {
	v := m.category
	if v == nil {
		return
	}
	return *v, true
}

// OldCategory returns the old "category" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldCategory(ctx context.Context) (v storeapp.Category, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategory: %w", err)
	}
	return oldValue.Category, nil
}

// ResetCategory resets all changes to the "category" field.
func (m *StoreAppMutation) ResetCategory() {
	m.category = nil
}

// SetRating sets the "rating" field.
func (m *StoreAppMutation) SetRating(f float32) {
	m.rating = &f
	m.addrating = nil
}

// Rating returns the value of the "rating" field in the mutation.
func (m *StoreAppMutation) Rating() (r float32, exists bool) {
	v := m.rating
	if v == nil {
		return
	}
	return *v, true
}

// OldRating returns the old "rating" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldRating(ctx context.Context) (v *float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRating: %w", err)
	}
	return oldValue.Rating, nil
}

// AddRating adds f to the "rating" field.
func (m *StoreAppMutation) AddRating(f float32) {
	if m.addrating != nil {
		*m.addrating += f
	} else {
		m.addrating = &f
	}
}

// AddedRating returns the value that was added to the "rating" field in this mutation.
func (m *StoreAppMutation) AddedRating() (r float32, exists bool) {
	v := m.addrating
	if v == nil {
		return
	}
	return *v, true
}

// ResetRating resets all changes to the "rating" field.
func (m *StoreAppMutation) ResetRating() {
	m.rating = nil
	m.addrating = nil
}

// SetReviews sets the "reviews" field.
func (m *StoreAppMutation) SetReviews(i int32) {
	m.reviews = &i
	m.addreviews = nil
}

// Reviews returns the value of the "reviews" field in the mutation.
func (m *StoreAppMutation) Reviews() (r int32, exists bool) {
	v := m.reviews
	if v == nil {
		return
	}
	return *v, true
}

// OldReviews returns the old "reviews" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldReviews(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReviews is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReviews requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReviews: %w", err)
	}
	return oldValue.Reviews, nil
}

// AddReviews adds i to the "reviews" field.
func (m *StoreAppMutation) AddReviews(i int32) {
	if m.addreviews != nil {
		*m.addreviews += i
	} else {
		m.addreviews = &i
	}
}

// AddedReviews returns the value that was added to the "reviews" field in this mutation.
func (m *StoreAppMutation) AddedReviews() (r int32, exists bool) {
	v := m.addreviews
	if v == nil {
		return
	}
	return *v, true
}

// ResetReviews resets all changes to the "reviews" field.
func (m *StoreAppMutation) ResetReviews() {
	m.reviews = nil
	m.addreviews = nil
}

// SetSize sets the "size" field.
func (m *StoreAppMutation) SetSize(s string) {
	m.size = &s
}

// Size returns the value of the "size" field in the mutation.
func (m *StoreAppMutation) Size() (r string, exists bool) {
	v := m.size
	if v == nil {
		return
	}
	return *v, true
}

// OldSize returns the old "size" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldSize(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSize is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSize requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSize: %w", err)
	}
	return oldValue.Size, nil
}

// ResetSize resets all changes to the "size" field.
func (m *StoreAppMutation) ResetSize() {
	m.size = nil
}

// SetInstalls sets the "installs" field.
func (m *StoreAppMutation) SetInstalls(s string) {
	m.installs = &s
}

// Installs returns the value of the "installs" field in the mutation.
func (m *StoreAppMutation) Installs() (r string, exists bool) {
	v := m.installs
	if v == nil {
		return
	}
	return *v, true
}

// OldInstalls returns the old "installs" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldInstalls(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstalls is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstalls requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstalls: %w", err)
	}
	return oldValue.Installs, nil
}

// ResetInstalls resets all changes to the "installs" field.
func (m *StoreAppMutation) ResetInstalls() {
	m.installs = nil
}

// SetType sets the "type" field.
func (m *StoreAppMutation) SetType(s storeapp.Type) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *StoreAppMutation) GetType() (r storeapp.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldType(ctx context.Context) (v storeapp.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *StoreAppMutation) ResetType() {
	m._type = nil
}

// SetPrice sets the "price" field.
func (m *StoreAppMutation) SetPrice(f float32) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *StoreAppMutation) Price() (r float32, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldPrice(ctx context.Context) (v float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *StoreAppMutation) AddPrice(f float32) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *StoreAppMutation) AddedPrice() (r float32, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *StoreAppMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetContentRating sets the "content_rating" field.
func (m *StoreAppMutation) SetContentRating(s string) {
	m.content_rating = &s
}

// ContentRating returns the value of the "content_rating" field in the mutation.
func (m *StoreAppMutation) ContentRating() (r string, exists bool) {
	v := m.content_rating
	if v == nil {
		return
	}
	return *v, true
}

// OldContentRating returns the old "content_rating" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldContentRating(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContentRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContentRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContentRating: %w", err)
	}
	return oldValue.ContentRating, nil
}

// ResetContentRating resets all changes to the "content_rating" field.
func (m *StoreAppMutation) ResetContentRating() {
	m.content_rating = nil
}

// SetLastUpdated sets the "last_updated" field.
func (m *StoreAppMutation) SetLastUpdated(s string) {
	m.last_updated = &s
}

// LastUpdated returns the value of the "last_updated" field in the mutation.
func (m *StoreAppMutation) LastUpdated() (r string, exists bool) {
	v := m.last_updated
	if v == nil {
		return
	}
	return *v, true
}

// OldLastUpdated returns the old "last_updated" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldLastUpdated(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastUpdated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastUpdated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastUpdated: %w", err)
	}
	return oldValue.LastUpdated, nil
}

// ResetLastUpdated resets all changes to the "last_updated" field.
func (m *StoreAppMutation) ResetLastUpdated() {
	m.last_updated = nil
}

// SetCurrentVer sets the "current_ver" field.
func (m *StoreAppMutation) SetCurrentVer(s string) {
	m.current_ver = &s
}

// CurrentVer returns the value of the "current_ver" field in the mutation.
func (m *StoreAppMutation) CurrentVer() (r string, exists bool) {
	v := m.current_ver
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrentVer returns the old "current_ver" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldCurrentVer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrentVer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrentVer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrentVer: %w", err)
	}
	return oldValue.CurrentVer, nil
}

// ResetCurrentVer resets all changes to the "current_ver" field.
func (m *StoreAppMutation) ResetCurrentVer() {
	m.current_ver = nil
}

// SetInAppPurchases sets the "in_app_purchases" field.
func (m *StoreAppMutation) SetInAppPurchases(b bool) {
	m.in_app_purchases = &b
}

// InAppPurchases returns the value of the "in_app_purchases" field in the mutation.
func (m *StoreAppMutation) InAppPurchases() (r bool, exists bool) {
	v := m.in_app_purchases
	if v == nil {
		return
	}
	return *v, true
}

// OldInAppPurchases returns the old "in_app_purchases" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldInAppPurchases(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInAppPurchases is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInAppPurchases requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInAppPurchases: %w", err)
	}
	return oldValue.InAppPurchases, nil
}

// ResetInAppPurchases resets all changes to the "in_app_purchases" field.
func (m *StoreAppMutation) ResetInAppPurchases() {
	m.in_app_purchases = nil
}

// SetAdSupported sets the "ad_supported" field.
func (m *StoreAppMutation) SetAdSupported(b bool) {
	m.ad_supported = &b
}

// AdSupported returns the value of the "ad_supported" field in the mutation.
func (m *StoreAppMutation) AdSupported() (r bool, exists bool) {
	v := m.ad_supported
	if v == nil {
		return
	}
	return *v, true
}

// OldAdSupported returns the old "ad_supported" field's value of the StoreApp entity.
// If the StoreApp object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreAppMutation) OldAdSupported(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAdSupported is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAdSupported requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAdSupported: %w", err)
	}
	return oldValue.AdSupported, nil
}

// ResetAdSupported resets all changes to the "ad_supported" field.
func (m *StoreAppMutation) ResetAdSupported() {
	m.ad_supported = nil
}

// AddGenreIDs adds the "genres" edge to the StoreGenre entity by ids.
func (m *StoreAppMutation) AddGenreIDs(ids ...uuid.UUID) {
	if m.genres == nil {
		m.genres = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.genres[ids[i]] = struct{}{}
	}
}

// ClearGenres clears the "genres" edge to the StoreGenre entity.
func (m *StoreAppMutation) ClearGenres() {
	m.clearedgenres = true
}

// GenresCleared reports if the "genres" edge to the StoreGenre entity was cleared.
func (m *StoreAppMutation) GenresCleared() bool {
	return m.clearedgenres
}

// RemoveGenreIDs removes the "genres" edge to the StoreGenre entity by IDs.
func (m *StoreAppMutation) RemoveGenreIDs(ids ...uuid.UUID) {
	if m.removedgenres == nil {
		m.removedgenres = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.genres, ids[i])
		m.removedgenres[ids[i]] = struct{}{}
	}
}

// RemovedGenres returns the removed IDs of the "genres" edge to the StoreGenre entity.
func (m *StoreAppMutation) RemovedGenresIDs() (ids []uuid.UUID) {
	for id := range m.removedgenres {
		ids = append(ids, id)
	}
	return
}

// GenresIDs returns the "genres" edge IDs in the mutation.
func (m *StoreAppMutation) GenresIDs() (ids []uuid.UUID) {
	for id := range m.genres {
		ids = append(ids, id)
	}
	return
}

// ResetGenres resets all changes to the "genres" edge.
func (m *StoreAppMutation) ResetGenres() {
	m.genres = nil
	m.clearedgenres = false
	m.removedgenres = nil
}

// Where appends a list predicates to the StoreAppMutation builder.
func (m *StoreAppMutation) Where(ps ...predicate.StoreApp) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StoreAppMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StoreAppMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.StoreApp, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StoreAppMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StoreAppMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (StoreApp).
func (m *StoreAppMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StoreAppMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.name != nil {
		fields = append(fields, storeapp.FieldName)
	}
	if m.category != nil {
		fields = append(fields, storeapp.FieldCategory)
	}
	if m.rating != nil {
		fields = append(fields, storeapp.FieldRating)
	}
	if m.reviews != nil {
		fields = append(fields, storeapp.FieldReviews)
	}
	if m.size != nil {
		fields = append(fields, storeapp.FieldSize)
	}
	if m.installs != nil {
		fields = append(fields, storeapp.FieldInstalls)
	}
	if m._type != nil {
		fields = append(fields, storeapp.FieldType)
	}
	if m.price != nil {
		fields = append(fields, storeapp.FieldPrice)
	}
	if m.content_rating != nil {
		fields = append(fields, storeapp.FieldContentRating)
	}
	if m.last_updated != nil {
		fields = append(fields, storeapp.FieldLastUpdated)
	}
	if m.current_ver != nil {
		fields = append(fields, storeapp.FieldCurrentVer)
	}
	if m.in_app_purchases != nil {
		fields = append(fields, storeapp.FieldInAppPurchases)
	}
	if m.ad_supported != nil {
		fields = append(fields, storeapp.FieldAdSupported)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StoreAppMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case storeapp.FieldName:
		return m.Name()
	case storeapp.FieldCategory:
		return m.Category()
	case storeapp.FieldRating:
		return m.Rating()
	case storeapp.FieldReviews:
		return m.Reviews()
	case storeapp.FieldSize:
		return m.Size()
	case storeapp.FieldInstalls:
		return m.Installs()
	case storeapp.FieldType:
		return m.GetType()
	case storeapp.FieldPrice:
		return m.Price()
	case storeapp.FieldContentRating:
		return m.ContentRating()
	case storeapp.FieldLastUpdated:
		return m.LastUpdated()
	case storeapp.FieldCurrentVer:
		return m.CurrentVer()
	case storeapp.FieldInAppPurchases:
		return m.InAppPurchases()
	case storeapp.FieldAdSupported:
		return m.AdSupported()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StoreAppMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case storeapp.FieldName:
		return m.OldName(ctx)
	case storeapp.FieldCategory:
		return m.OldCategory(ctx)
	case storeapp.FieldRating:
		return m.OldRating(ctx)
	case storeapp.FieldReviews:
		return m.OldReviews(ctx)
	case storeapp.FieldSize:
		return m.OldSize(ctx)
	case storeapp.FieldInstalls:
		return m.OldInstalls(ctx)
	case storeapp.FieldType:
		return m.OldType(ctx)
	case storeapp.FieldPrice:
		return m.OldPrice(ctx)
	case storeapp.FieldContentRating:
		return m.OldContentRating(ctx)
	case storeapp.FieldLastUpdated:
		return m.OldLastUpdated(ctx)
	case storeapp.FieldCurrentVer:
		return m.OldCurrentVer(ctx)
	case storeapp.FieldInAppPurchases:
		return m.OldInAppPurchases(ctx)
	case storeapp.FieldAdSupported:
		return m.OldAdSupported(ctx)
	}
	return nil, fmt.Errorf("unknown StoreApp field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreAppMutation) SetField(name string, value ent.Value) error {
	switch name {
	case storeapp.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case storeapp.FieldCategory:
		v, ok := value.(storeapp.Category)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategory(v)
		return nil
	case storeapp.FieldRating:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRating(v)
		return nil
	case storeapp.FieldReviews:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReviews(v)
		return nil
	case storeapp.FieldSize:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSize(v)
		return nil
	case storeapp.FieldInstalls:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstalls(v)
		return nil
	case storeapp.FieldType:
		v, ok := value.(storeapp.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case storeapp.FieldPrice:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case storeapp.FieldContentRating:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContentRating(v)
		return nil
	case storeapp.FieldLastUpdated:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastUpdated(v)
		return nil
	case storeapp.FieldCurrentVer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrentVer(v)
		return nil
	case storeapp.FieldInAppPurchases:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInAppPurchases(v)
		return nil
	case storeapp.FieldAdSupported:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAdSupported(v)
		return nil
	}
	return fmt.Errorf("unknown StoreApp field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StoreAppMutation) AddedFields() []string {
	var fields []string
	if m.addrating != nil {
		fields = append(fields, storeapp.FieldRating)
	}
	if m.addreviews != nil {
		fields = append(fields, storeapp.FieldReviews)
	}
	if m.addprice != nil {
		fields = append(fields, storeapp.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StoreAppMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case storeapp.FieldRating:
		return m.AddedRating()
	case storeapp.FieldReviews:
		return m.AddedReviews()
	case storeapp.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreAppMutation) AddField(name string, value ent.Value) error {
	switch name {
	case storeapp.FieldRating:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRating(v)
		return nil
	case storeapp.FieldReviews:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddReviews(v)
		return nil
	case storeapp.FieldPrice:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown StoreApp numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StoreAppMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StoreAppMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StoreAppMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StoreApp nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StoreAppMutation) ResetField(name string) error {
	switch name {
	case storeapp.FieldName:
		m.ResetName()
		return nil
	case storeapp.FieldCategory:
		m.ResetCategory()
		return nil
	case storeapp.FieldRating:
		m.ResetRating()
		return nil
	case storeapp.FieldReviews:
		m.ResetReviews()
		return nil
	case storeapp.FieldSize:
		m.ResetSize()
		return nil
	case storeapp.FieldInstalls:
		m.ResetInstalls()
		return nil
	case storeapp.FieldType:
		m.ResetType()
		return nil
	case storeapp.FieldPrice:
		m.ResetPrice()
		return nil
	case storeapp.FieldContentRating:
		m.ResetContentRating()
		return nil
	case storeapp.FieldLastUpdated:
		m.ResetLastUpdated()
		return nil
	case storeapp.FieldCurrentVer:
		m.ResetCurrentVer()
		return nil
	case storeapp.FieldInAppPurchases:
		m.ResetInAppPurchases()
		return nil
	case storeapp.FieldAdSupported:
		m.ResetAdSupported()
		return nil
	}
	return fmt.Errorf("unknown StoreApp field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StoreAppMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.genres != nil {
		edges = append(edges, storeapp.EdgeGenres)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StoreAppMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case storeapp.EdgeGenres:
		ids := make([]ent.Value, 0, len(m.genres))
		for id := range m.genres {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StoreAppMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedgenres != nil {
		edges = append(edges, storeapp.EdgeGenres)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StoreAppMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case storeapp.EdgeGenres:
		ids := make([]ent.Value, 0, len(m.removedgenres))
		for id := range m.removedgenres {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StoreAppMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedgenres {
		edges = append(edges, storeapp.EdgeGenres)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StoreAppMutation) EdgeCleared(name string) bool {
	switch name {
	case storeapp.EdgeGenres:
		return m.clearedgenres
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StoreAppMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown StoreApp unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StoreAppMutation) ResetEdge(name string) error {
	switch name {
	case storeapp.EdgeGenres:
		m.ResetGenres()
		return nil
	}
	return fmt.Errorf("unknown StoreApp edge %s", name)
}

// StoreGenreMutation represents an operation that mutates the StoreGenre nodes in the graph.
type StoreGenreMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	clearedFields map[string]struct{}
	app           map[uuid.UUID]struct{}
	removedapp    map[uuid.UUID]struct{}
	clearedapp    bool
	done          bool
	oldValue      func(context.Context) (*StoreGenre, error)
	predicates    []predicate.StoreGenre
}

var _ ent.Mutation = (*StoreGenreMutation)(nil)

// storegenreOption allows management of the mutation configuration using functional options.
type storegenreOption func(*StoreGenreMutation)

// newStoreGenreMutation creates new mutation for the StoreGenre entity.
func newStoreGenreMutation(c config, op Op, opts ...storegenreOption) *StoreGenreMutation {
	m := &StoreGenreMutation{
		config:        c,
		op:            op,
		typ:           TypeStoreGenre,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStoreGenreID sets the ID field of the mutation.
func withStoreGenreID(id uuid.UUID) storegenreOption {
	return func(m *StoreGenreMutation) {
		var (
			err   error
			once  sync.Once
			value *StoreGenre
		)
		m.oldValue = func(ctx context.Context) (*StoreGenre, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StoreGenre.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStoreGenre sets the old StoreGenre of the mutation.
func withStoreGenre(node *StoreGenre) storegenreOption {
	return func(m *StoreGenreMutation) {
		m.oldValue = func(context.Context) (*StoreGenre, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StoreGenreMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StoreGenreMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entities: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of StoreGenre entities.
func (m *StoreGenreMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StoreGenreMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StoreGenreMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().StoreGenre.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *StoreGenreMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *StoreGenreMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the StoreGenre entity.
// If the StoreGenre object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreGenreMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *StoreGenreMutation) ResetName() {
	m.name = nil
}

// AddAppIDs adds the "app" edge to the StoreApp entity by ids.
func (m *StoreGenreMutation) AddAppIDs(ids ...uuid.UUID) {
	if m.app == nil {
		m.app = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.app[ids[i]] = struct{}{}
	}
}

// ClearApp clears the "app" edge to the StoreApp entity.
func (m *StoreGenreMutation) ClearApp() {
	m.clearedapp = true
}

// AppCleared reports if the "app" edge to the StoreApp entity was cleared.
func (m *StoreGenreMutation) AppCleared() bool {
	return m.clearedapp
}

// RemoveAppIDs removes the "app" edge to the StoreApp entity by IDs.
func (m *StoreGenreMutation) RemoveAppIDs(ids ...uuid.UUID) {
	if m.removedapp == nil {
		m.removedapp = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.app, ids[i])
		m.removedapp[ids[i]] = struct{}{}
	}
}

// RemovedApp returns the removed IDs of the "app" edge to the StoreApp entity.
func (m *StoreGenreMutation) RemovedAppIDs() (ids []uuid.UUID) {
	for id := range m.removedapp {
		ids = append(ids, id)
	}
	return
}

// AppIDs returns the "app" edge IDs in the mutation.
func (m *StoreGenreMutation) AppIDs() (ids []uuid.UUID) {
	for id := range m.app {
		ids = append(ids, id)
	}
	return
}

// ResetApp resets all changes to the "app" edge.
func (m *StoreGenreMutation) ResetApp() {
	m.app = nil
	m.clearedapp = false
	m.removedapp = nil
}

// Where appends a list predicates to the StoreGenreMutation builder.
func (m *StoreGenreMutation) Where(ps ...predicate.StoreGenre) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StoreGenreMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StoreGenreMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.StoreGenre, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StoreGenreMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StoreGenreMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (StoreGenre).
func (m *StoreGenreMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StoreGenreMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, storegenre.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StoreGenreMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case storegenre.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StoreGenreMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case storegenre.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown StoreGenre field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreGenreMutation) SetField(name string, value ent.Value) error {
	switch name {
	case storegenre.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown StoreGenre field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StoreGenreMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StoreGenreMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreGenreMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown StoreGenre numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StoreGenreMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StoreGenreMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StoreGenreMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StoreGenre nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StoreGenreMutation) ResetField(name string) error {
	switch name {
	case storegenre.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown StoreGenre field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StoreGenreMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.app != nil {
		edges = append(edges, storegenre.EdgeApp)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StoreGenreMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case storegenre.EdgeApp:
		ids := make([]ent.Value, 0, len(m.app))
		for id := range m.app {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StoreGenreMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedapp != nil {
		edges = append(edges, storegenre.EdgeApp)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StoreGenreMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case storegenre.EdgeApp:
		ids := make([]ent.Value, 0, len(m.removedapp))
		for id := range m.removedapp {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StoreGenreMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedapp {
		edges = append(edges, storegenre.EdgeApp)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StoreGenreMutation) EdgeCleared(name string) bool {
	switch name {
	case storegenre.EdgeApp:
		return m.clearedapp
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StoreGenreMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown StoreGenre unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StoreGenreMutation) ResetEdge(name string) error {
	switch name {
	case storegenre.EdgeApp:
		m.ResetApp()
		return nil
	}
	return fmt.Errorf("unknown StoreGenre edge %s", name)
}

// WywwGenreMutation represents an operation that mutates the WywwGenre nodes in the graph.
type WywwGenreMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	clearedFields map[string]struct{}
	app           map[uuid.UUID]struct{}
	removedapp    map[uuid.UUID]struct{}
	clearedapp    bool
	done          bool
	oldValue      func(context.Context) (*WywwGenre, error)
	predicates    []predicate.WywwGenre
}

var _ ent.Mutation = (*WywwGenreMutation)(nil)

// wywwgenreOption allows management of the mutation configuration using functional options.
type wywwgenreOption func(*WywwGenreMutation)

// newWywwGenreMutation creates new mutation for the WywwGenre entity.
func newWywwGenreMutation(c config, op Op, opts ...wywwgenreOption) *WywwGenreMutation {
	m := &WywwGenreMutation{
		config:        c,
		op:            op,
		typ:           TypeWywwGenre,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withWywwGenreID sets the ID field of the mutation.
func withWywwGenreID(id uuid.UUID) wywwgenreOption {
	return func(m *WywwGenreMutation) {
		var (
			err   error
			once  sync.Once
			value *WywwGenre
		)
		m.oldValue = func(ctx context.Context) (*WywwGenre, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().WywwGenre.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withWywwGenre sets the old WywwGenre of the mutation.
func withWywwGenre(node *WywwGenre) wywwgenreOption {
	return func(m *WywwGenreMutation) {
		m.oldValue = func(context.Context) (*WywwGenre, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m WywwGenreMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m WywwGenreMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entities: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of WywwGenre entities.
func (m *WywwGenreMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *WywwGenreMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *WywwGenreMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().WywwGenre.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *WywwGenreMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *WywwGenreMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the WywwGenre entity.
// If the WywwGenre object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwGenreMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *WywwGenreMutation) ResetName() {
	m.name = nil
}

// AddAppIDs adds the "app" edge to the WywwMovie entity by ids.
func (m *WywwGenreMutation) AddAppIDs(ids ...uuid.UUID) {
	if m.app == nil {
		m.app = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.app[ids[i]] = struct{}{}
	}
}

// ClearApp clears the "app" edge to the WywwMovie entity.
func (m *WywwGenreMutation) ClearApp() {
	m.clearedapp = true
}

// AppCleared reports if the "app" edge to the WywwMovie entity was cleared.
func (m *WywwGenreMutation) AppCleared() bool {
	return m.clearedapp
}

// RemoveAppIDs removes the "app" edge to the WywwMovie entity by IDs.
func (m *WywwGenreMutation) RemoveAppIDs(ids ...uuid.UUID) {
	if m.removedapp == nil {
		m.removedapp = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.app, ids[i])
		m.removedapp[ids[i]] = struct{}{}
	}
}

// RemovedApp returns the removed IDs of the "app" edge to the WywwMovie entity.
func (m *WywwGenreMutation) RemovedAppIDs() (ids []uuid.UUID) {
	for id := range m.removedapp {
		ids = append(ids, id)
	}
	return
}

// AppIDs returns the "app" edge IDs in the mutation.
func (m *WywwGenreMutation) AppIDs() (ids []uuid.UUID) {
	for id := range m.app {
		ids = append(ids, id)
	}
	return
}

// ResetApp resets all changes to the "app" edge.
func (m *WywwGenreMutation) ResetApp() {
	m.app = nil
	m.clearedapp = false
	m.removedapp = nil
}

// Where appends a list predicates to the WywwGenreMutation builder.
func (m *WywwGenreMutation) Where(ps ...predicate.WywwGenre) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the WywwGenreMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *WywwGenreMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.WywwGenre, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *WywwGenreMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *WywwGenreMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (WywwGenre).
func (m *WywwGenreMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *WywwGenreMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, wywwgenre.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *WywwGenreMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case wywwgenre.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *WywwGenreMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case wywwgenre.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown WywwGenre field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WywwGenreMutation) SetField(name string, value ent.Value) error {
	switch name {
	case wywwgenre.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown WywwGenre field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *WywwGenreMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *WywwGenreMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WywwGenreMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown WywwGenre numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *WywwGenreMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *WywwGenreMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *WywwGenreMutation) ClearField(name string) error {
	return fmt.Errorf("unknown WywwGenre nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *WywwGenreMutation) ResetField(name string) error {
	switch name {
	case wywwgenre.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown WywwGenre field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *WywwGenreMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.app != nil {
		edges = append(edges, wywwgenre.EdgeApp)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *WywwGenreMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case wywwgenre.EdgeApp:
		ids := make([]ent.Value, 0, len(m.app))
		for id := range m.app {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *WywwGenreMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedapp != nil {
		edges = append(edges, wywwgenre.EdgeApp)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *WywwGenreMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case wywwgenre.EdgeApp:
		ids := make([]ent.Value, 0, len(m.removedapp))
		for id := range m.removedapp {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *WywwGenreMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedapp {
		edges = append(edges, wywwgenre.EdgeApp)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *WywwGenreMutation) EdgeCleared(name string) bool {
	switch name {
	case wywwgenre.EdgeApp:
		return m.clearedapp
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *WywwGenreMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown WywwGenre unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *WywwGenreMutation) ResetEdge(name string) error {
	switch name {
	case wywwgenre.EdgeApp:
		m.ResetApp()
		return nil
	}
	return fmt.Errorf("unknown WywwGenre edge %s", name)
}

// WywwMovieMutation represents an operation that mutates the WywwMovie nodes in the graph.
type WywwMovieMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	movie_title      *string
	original_title   *string
	content_rating   *wywwmovie.ContentRating
	description      *string
	poster_path      *string
	banner_path      *string
	released_year    *int32
	addreleased_year *int32
	runtime          *int32
	addruntime       *int32
	rating           *float32
	addrating        *float32
	clearedFields    map[string]struct{}
	genres           map[uuid.UUID]struct{}
	removedgenres    map[uuid.UUID]struct{}
	clearedgenres    bool
	done             bool
	oldValue         func(context.Context) (*WywwMovie, error)
	predicates       []predicate.WywwMovie
}

var _ ent.Mutation = (*WywwMovieMutation)(nil)

// wywwmovieOption allows management of the mutation configuration using functional options.
type wywwmovieOption func(*WywwMovieMutation)

// newWywwMovieMutation creates new mutation for the WywwMovie entity.
func newWywwMovieMutation(c config, op Op, opts ...wywwmovieOption) *WywwMovieMutation {
	m := &WywwMovieMutation{
		config:        c,
		op:            op,
		typ:           TypeWywwMovie,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withWywwMovieID sets the ID field of the mutation.
func withWywwMovieID(id uuid.UUID) wywwmovieOption {
	return func(m *WywwMovieMutation) {
		var (
			err   error
			once  sync.Once
			value *WywwMovie
		)
		m.oldValue = func(ctx context.Context) (*WywwMovie, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().WywwMovie.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withWywwMovie sets the old WywwMovie of the mutation.
func withWywwMovie(node *WywwMovie) wywwmovieOption {
	return func(m *WywwMovieMutation) {
		m.oldValue = func(context.Context) (*WywwMovie, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m WywwMovieMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m WywwMovieMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("entities: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of WywwMovie entities.
func (m *WywwMovieMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *WywwMovieMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *WywwMovieMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().WywwMovie.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetMovieTitle sets the "movie_title" field.
func (m *WywwMovieMutation) SetMovieTitle(s string) {
	m.movie_title = &s
}

// MovieTitle returns the value of the "movie_title" field in the mutation.
func (m *WywwMovieMutation) MovieTitle() (r string, exists bool) {
	v := m.movie_title
	if v == nil {
		return
	}
	return *v, true
}

// OldMovieTitle returns the old "movie_title" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldMovieTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMovieTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMovieTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMovieTitle: %w", err)
	}
	return oldValue.MovieTitle, nil
}

// ResetMovieTitle resets all changes to the "movie_title" field.
func (m *WywwMovieMutation) ResetMovieTitle() {
	m.movie_title = nil
}

// SetOriginalTitle sets the "original_title" field.
func (m *WywwMovieMutation) SetOriginalTitle(s string) {
	m.original_title = &s
}

// OriginalTitle returns the value of the "original_title" field in the mutation.
func (m *WywwMovieMutation) OriginalTitle() (r string, exists bool) {
	v := m.original_title
	if v == nil {
		return
	}
	return *v, true
}

// OldOriginalTitle returns the old "original_title" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldOriginalTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOriginalTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOriginalTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOriginalTitle: %w", err)
	}
	return oldValue.OriginalTitle, nil
}

// ResetOriginalTitle resets all changes to the "original_title" field.
func (m *WywwMovieMutation) ResetOriginalTitle() {
	m.original_title = nil
}

// SetContentRating sets the "content_rating" field.
func (m *WywwMovieMutation) SetContentRating(wr wywwmovie.ContentRating) {
	m.content_rating = &wr
}

// ContentRating returns the value of the "content_rating" field in the mutation.
func (m *WywwMovieMutation) ContentRating() (r wywwmovie.ContentRating, exists bool) {
	v := m.content_rating
	if v == nil {
		return
	}
	return *v, true
}

// OldContentRating returns the old "content_rating" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldContentRating(ctx context.Context) (v wywwmovie.ContentRating, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContentRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContentRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContentRating: %w", err)
	}
	return oldValue.ContentRating, nil
}

// ResetContentRating resets all changes to the "content_rating" field.
func (m *WywwMovieMutation) ResetContentRating() {
	m.content_rating = nil
}

// SetDescription sets the "description" field.
func (m *WywwMovieMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *WywwMovieMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *WywwMovieMutation) ResetDescription() {
	m.description = nil
}

// SetPosterPath sets the "poster_path" field.
func (m *WywwMovieMutation) SetPosterPath(s string) {
	m.poster_path = &s
}

// PosterPath returns the value of the "poster_path" field in the mutation.
func (m *WywwMovieMutation) PosterPath() (r string, exists bool) {
	v := m.poster_path
	if v == nil {
		return
	}
	return *v, true
}

// OldPosterPath returns the old "poster_path" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldPosterPath(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPosterPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPosterPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPosterPath: %w", err)
	}
	return oldValue.PosterPath, nil
}

// ResetPosterPath resets all changes to the "poster_path" field.
func (m *WywwMovieMutation) ResetPosterPath() {
	m.poster_path = nil
}

// SetBannerPath sets the "banner_path" field.
func (m *WywwMovieMutation) SetBannerPath(s string) {
	m.banner_path = &s
}

// BannerPath returns the value of the "banner_path" field in the mutation.
func (m *WywwMovieMutation) BannerPath() (r string, exists bool) {
	v := m.banner_path
	if v == nil {
		return
	}
	return *v, true
}

// OldBannerPath returns the old "banner_path" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldBannerPath(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBannerPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBannerPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBannerPath: %w", err)
	}
	return oldValue.BannerPath, nil
}

// ResetBannerPath resets all changes to the "banner_path" field.
func (m *WywwMovieMutation) ResetBannerPath() {
	m.banner_path = nil
}

// SetReleasedYear sets the "released_year" field.
func (m *WywwMovieMutation) SetReleasedYear(i int32) {
	m.released_year = &i
	m.addreleased_year = nil
}

// ReleasedYear returns the value of the "released_year" field in the mutation.
func (m *WywwMovieMutation) ReleasedYear() (r int32, exists bool) {
	v := m.released_year
	if v == nil {
		return
	}
	return *v, true
}

// OldReleasedYear returns the old "released_year" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldReleasedYear(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReleasedYear is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReleasedYear requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReleasedYear: %w", err)
	}
	return oldValue.ReleasedYear, nil
}

// AddReleasedYear adds i to the "released_year" field.
func (m *WywwMovieMutation) AddReleasedYear(i int32) {
	if m.addreleased_year != nil {
		*m.addreleased_year += i
	} else {
		m.addreleased_year = &i
	}
}

// AddedReleasedYear returns the value that was added to the "released_year" field in this mutation.
func (m *WywwMovieMutation) AddedReleasedYear() (r int32, exists bool) {
	v := m.addreleased_year
	if v == nil {
		return
	}
	return *v, true
}

// ResetReleasedYear resets all changes to the "released_year" field.
func (m *WywwMovieMutation) ResetReleasedYear() {
	m.released_year = nil
	m.addreleased_year = nil
}

// SetRuntime sets the "runtime" field.
func (m *WywwMovieMutation) SetRuntime(i int32) {
	m.runtime = &i
	m.addruntime = nil
}

// Runtime returns the value of the "runtime" field in the mutation.
func (m *WywwMovieMutation) Runtime() (r int32, exists bool) {
	v := m.runtime
	if v == nil {
		return
	}
	return *v, true
}

// OldRuntime returns the old "runtime" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldRuntime(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRuntime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRuntime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRuntime: %w", err)
	}
	return oldValue.Runtime, nil
}

// AddRuntime adds i to the "runtime" field.
func (m *WywwMovieMutation) AddRuntime(i int32) {
	if m.addruntime != nil {
		*m.addruntime += i
	} else {
		m.addruntime = &i
	}
}

// AddedRuntime returns the value that was added to the "runtime" field in this mutation.
func (m *WywwMovieMutation) AddedRuntime() (r int32, exists bool) {
	v := m.addruntime
	if v == nil {
		return
	}
	return *v, true
}

// ResetRuntime resets all changes to the "runtime" field.
func (m *WywwMovieMutation) ResetRuntime() {
	m.runtime = nil
	m.addruntime = nil
}

// SetRating sets the "rating" field.
func (m *WywwMovieMutation) SetRating(f float32) {
	m.rating = &f
	m.addrating = nil
}

// Rating returns the value of the "rating" field in the mutation.
func (m *WywwMovieMutation) Rating() (r float32, exists bool) {
	v := m.rating
	if v == nil {
		return
	}
	return *v, true
}

// OldRating returns the old "rating" field's value of the WywwMovie entity.
// If the WywwMovie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WywwMovieMutation) OldRating(ctx context.Context) (v float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRating is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRating requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRating: %w", err)
	}
	return oldValue.Rating, nil
}

// AddRating adds f to the "rating" field.
func (m *WywwMovieMutation) AddRating(f float32) {
	if m.addrating != nil {
		*m.addrating += f
	} else {
		m.addrating = &f
	}
}

// AddedRating returns the value that was added to the "rating" field in this mutation.
func (m *WywwMovieMutation) AddedRating() (r float32, exists bool) {
	v := m.addrating
	if v == nil {
		return
	}
	return *v, true
}

// ResetRating resets all changes to the "rating" field.
func (m *WywwMovieMutation) ResetRating() {
	m.rating = nil
	m.addrating = nil
}

// AddGenreIDs adds the "genres" edge to the WywwGenre entity by ids.
func (m *WywwMovieMutation) AddGenreIDs(ids ...uuid.UUID) {
	if m.genres == nil {
		m.genres = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.genres[ids[i]] = struct{}{}
	}
}

// ClearGenres clears the "genres" edge to the WywwGenre entity.
func (m *WywwMovieMutation) ClearGenres() {
	m.clearedgenres = true
}

// GenresCleared reports if the "genres" edge to the WywwGenre entity was cleared.
func (m *WywwMovieMutation) GenresCleared() bool {
	return m.clearedgenres
}

// RemoveGenreIDs removes the "genres" edge to the WywwGenre entity by IDs.
func (m *WywwMovieMutation) RemoveGenreIDs(ids ...uuid.UUID) {
	if m.removedgenres == nil {
		m.removedgenres = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.genres, ids[i])
		m.removedgenres[ids[i]] = struct{}{}
	}
}

// RemovedGenres returns the removed IDs of the "genres" edge to the WywwGenre entity.
func (m *WywwMovieMutation) RemovedGenresIDs() (ids []uuid.UUID) {
	for id := range m.removedgenres {
		ids = append(ids, id)
	}
	return
}

// GenresIDs returns the "genres" edge IDs in the mutation.
func (m *WywwMovieMutation) GenresIDs() (ids []uuid.UUID) {
	for id := range m.genres {
		ids = append(ids, id)
	}
	return
}

// ResetGenres resets all changes to the "genres" edge.
func (m *WywwMovieMutation) ResetGenres() {
	m.genres = nil
	m.clearedgenres = false
	m.removedgenres = nil
}

// Where appends a list predicates to the WywwMovieMutation builder.
func (m *WywwMovieMutation) Where(ps ...predicate.WywwMovie) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the WywwMovieMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *WywwMovieMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.WywwMovie, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *WywwMovieMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *WywwMovieMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (WywwMovie).
func (m *WywwMovieMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *WywwMovieMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.movie_title != nil {
		fields = append(fields, wywwmovie.FieldMovieTitle)
	}
	if m.original_title != nil {
		fields = append(fields, wywwmovie.FieldOriginalTitle)
	}
	if m.content_rating != nil {
		fields = append(fields, wywwmovie.FieldContentRating)
	}
	if m.description != nil {
		fields = append(fields, wywwmovie.FieldDescription)
	}
	if m.poster_path != nil {
		fields = append(fields, wywwmovie.FieldPosterPath)
	}
	if m.banner_path != nil {
		fields = append(fields, wywwmovie.FieldBannerPath)
	}
	if m.released_year != nil {
		fields = append(fields, wywwmovie.FieldReleasedYear)
	}
	if m.runtime != nil {
		fields = append(fields, wywwmovie.FieldRuntime)
	}
	if m.rating != nil {
		fields = append(fields, wywwmovie.FieldRating)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *WywwMovieMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case wywwmovie.FieldMovieTitle:
		return m.MovieTitle()
	case wywwmovie.FieldOriginalTitle:
		return m.OriginalTitle()
	case wywwmovie.FieldContentRating:
		return m.ContentRating()
	case wywwmovie.FieldDescription:
		return m.Description()
	case wywwmovie.FieldPosterPath:
		return m.PosterPath()
	case wywwmovie.FieldBannerPath:
		return m.BannerPath()
	case wywwmovie.FieldReleasedYear:
		return m.ReleasedYear()
	case wywwmovie.FieldRuntime:
		return m.Runtime()
	case wywwmovie.FieldRating:
		return m.Rating()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *WywwMovieMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case wywwmovie.FieldMovieTitle:
		return m.OldMovieTitle(ctx)
	case wywwmovie.FieldOriginalTitle:
		return m.OldOriginalTitle(ctx)
	case wywwmovie.FieldContentRating:
		return m.OldContentRating(ctx)
	case wywwmovie.FieldDescription:
		return m.OldDescription(ctx)
	case wywwmovie.FieldPosterPath:
		return m.OldPosterPath(ctx)
	case wywwmovie.FieldBannerPath:
		return m.OldBannerPath(ctx)
	case wywwmovie.FieldReleasedYear:
		return m.OldReleasedYear(ctx)
	case wywwmovie.FieldRuntime:
		return m.OldRuntime(ctx)
	case wywwmovie.FieldRating:
		return m.OldRating(ctx)
	}
	return nil, fmt.Errorf("unknown WywwMovie field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WywwMovieMutation) SetField(name string, value ent.Value) error {
	switch name {
	case wywwmovie.FieldMovieTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMovieTitle(v)
		return nil
	case wywwmovie.FieldOriginalTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOriginalTitle(v)
		return nil
	case wywwmovie.FieldContentRating:
		v, ok := value.(wywwmovie.ContentRating)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContentRating(v)
		return nil
	case wywwmovie.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case wywwmovie.FieldPosterPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPosterPath(v)
		return nil
	case wywwmovie.FieldBannerPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBannerPath(v)
		return nil
	case wywwmovie.FieldReleasedYear:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReleasedYear(v)
		return nil
	case wywwmovie.FieldRuntime:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRuntime(v)
		return nil
	case wywwmovie.FieldRating:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRating(v)
		return nil
	}
	return fmt.Errorf("unknown WywwMovie field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *WywwMovieMutation) AddedFields() []string {
	var fields []string
	if m.addreleased_year != nil {
		fields = append(fields, wywwmovie.FieldReleasedYear)
	}
	if m.addruntime != nil {
		fields = append(fields, wywwmovie.FieldRuntime)
	}
	if m.addrating != nil {
		fields = append(fields, wywwmovie.FieldRating)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *WywwMovieMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case wywwmovie.FieldReleasedYear:
		return m.AddedReleasedYear()
	case wywwmovie.FieldRuntime:
		return m.AddedRuntime()
	case wywwmovie.FieldRating:
		return m.AddedRating()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WywwMovieMutation) AddField(name string, value ent.Value) error {
	switch name {
	case wywwmovie.FieldReleasedYear:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddReleasedYear(v)
		return nil
	case wywwmovie.FieldRuntime:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRuntime(v)
		return nil
	case wywwmovie.FieldRating:
		v, ok := value.(float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRating(v)
		return nil
	}
	return fmt.Errorf("unknown WywwMovie numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *WywwMovieMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *WywwMovieMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *WywwMovieMutation) ClearField(name string) error {
	return fmt.Errorf("unknown WywwMovie nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *WywwMovieMutation) ResetField(name string) error {
	switch name {
	case wywwmovie.FieldMovieTitle:
		m.ResetMovieTitle()
		return nil
	case wywwmovie.FieldOriginalTitle:
		m.ResetOriginalTitle()
		return nil
	case wywwmovie.FieldContentRating:
		m.ResetContentRating()
		return nil
	case wywwmovie.FieldDescription:
		m.ResetDescription()
		return nil
	case wywwmovie.FieldPosterPath:
		m.ResetPosterPath()
		return nil
	case wywwmovie.FieldBannerPath:
		m.ResetBannerPath()
		return nil
	case wywwmovie.FieldReleasedYear:
		m.ResetReleasedYear()
		return nil
	case wywwmovie.FieldRuntime:
		m.ResetRuntime()
		return nil
	case wywwmovie.FieldRating:
		m.ResetRating()
		return nil
	}
	return fmt.Errorf("unknown WywwMovie field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *WywwMovieMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.genres != nil {
		edges = append(edges, wywwmovie.EdgeGenres)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *WywwMovieMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case wywwmovie.EdgeGenres:
		ids := make([]ent.Value, 0, len(m.genres))
		for id := range m.genres {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *WywwMovieMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedgenres != nil {
		edges = append(edges, wywwmovie.EdgeGenres)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *WywwMovieMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case wywwmovie.EdgeGenres:
		ids := make([]ent.Value, 0, len(m.removedgenres))
		for id := range m.removedgenres {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *WywwMovieMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedgenres {
		edges = append(edges, wywwmovie.EdgeGenres)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *WywwMovieMutation) EdgeCleared(name string) bool {
	switch name {
	case wywwmovie.EdgeGenres:
		return m.clearedgenres
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *WywwMovieMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown WywwMovie unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *WywwMovieMutation) ResetEdge(name string) error {
	switch name {
	case wywwmovie.EdgeGenres:
		m.ResetGenres()
		return nil
	}
	return fmt.Errorf("unknown WywwMovie edge %s", name)
}
