// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/storeapp"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// StoreApp is the model entity for the StoreApp schema.
type StoreApp struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Category holds the value of the "category" field.
	Category storeapp.Category `json:"category,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating *float32 `json:"rating,omitempty"`
	// Reviews holds the value of the "reviews" field.
	Reviews int32 `json:"reviews,omitempty"`
	// Size holds the value of the "size" field.
	Size string `json:"size,omitempty"`
	// Installs holds the value of the "installs" field.
	Installs string `json:"installs,omitempty"`
	// Type holds the value of the "type" field.
	Type storeapp.Type `json:"type,omitempty"`
	// Price holds the value of the "price" field.
	Price float32 `json:"price,omitempty"`
	// ContentRating holds the value of the "content_rating" field.
	ContentRating string `json:"content_rating,omitempty"`
	// LastUpdated holds the value of the "last_updated" field.
	LastUpdated string `json:"last_updated,omitempty"`
	// CurrentVer holds the value of the "current_ver" field.
	CurrentVer string `json:"current_ver,omitempty"`
	// InAppPurchases holds the value of the "in_app_purchases" field.
	InAppPurchases bool `json:"in_app_purchases,omitempty"`
	// AdSupported holds the value of the "ad_supported" field.
	AdSupported bool `json:"ad_supported,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StoreAppQuery when eager-loading is set.
	Edges        StoreAppEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StoreAppEdges holds the relations/edges for other nodes in the graph.
type StoreAppEdges struct {
	// Genres holds the value of the genres edge.
	Genres []*StoreGenre `json:"genres,omitempty"`
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// UserInstallList holds the value of the user_install_list edge.
	UserInstallList []*User `json:"user_install_list,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GenresOrErr returns the Genres value or an error if the edge
// was not loaded in eager-loading.
func (e StoreAppEdges) GenresOrErr() ([]*StoreGenre, error) {
	if e.loadedTypes[0] {
		return e.Genres, nil
	}
	return nil, &NotLoadedError{edge: "genres"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e StoreAppEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[1] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// UserInstallListOrErr returns the UserInstallList value or an error if the edge
// was not loaded in eager-loading.
func (e StoreAppEdges) UserInstallListOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.UserInstallList, nil
	}
	return nil, &NotLoadedError{edge: "user_install_list"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StoreApp) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storeapp.FieldInAppPurchases, storeapp.FieldAdSupported:
			values[i] = new(sql.NullBool)
		case storeapp.FieldRating, storeapp.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case storeapp.FieldReviews:
			values[i] = new(sql.NullInt64)
		case storeapp.FieldName, storeapp.FieldCategory, storeapp.FieldSize, storeapp.FieldInstalls, storeapp.FieldType, storeapp.FieldContentRating, storeapp.FieldLastUpdated, storeapp.FieldCurrentVer:
			values[i] = new(sql.NullString)
		case storeapp.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StoreApp fields.
func (_m *StoreApp) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storeapp.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case storeapp.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case storeapp.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = storeapp.Category(value.String)
			}
		case storeapp.FieldRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = new(float32)
				*_m.Rating = float32(value.Float64)
			}
		case storeapp.FieldReviews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviews", values[i])
			} else if value.Valid {
				_m.Reviews = int32(value.Int64)
			}
		case storeapp.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.String
			}
		case storeapp.FieldInstalls:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installs", values[i])
			} else if value.Valid {
				_m.Installs = value.String
			}
		case storeapp.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = storeapp.Type(value.String)
			}
		case storeapp.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = float32(value.Float64)
			}
		case storeapp.FieldContentRating:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_rating", values[i])
			} else if value.Valid {
				_m.ContentRating = value.String
			}
		case storeapp.FieldLastUpdated:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated", values[i])
			} else if value.Valid {
				_m.LastUpdated = value.String
			}
		case storeapp.FieldCurrentVer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_ver", values[i])
			} else if value.Valid {
				_m.CurrentVer = value.String
			}
		case storeapp.FieldInAppPurchases:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field in_app_purchases", values[i])
			} else if value.Valid {
				_m.InAppPurchases = value.Bool
			}
		case storeapp.FieldAdSupported:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ad_supported", values[i])
			} else if value.Valid {
				_m.AdSupported = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StoreApp.
// This includes values selected through modifiers, order, etc.
func (_m *StoreApp) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGenres queries the "genres" edge of the StoreApp entity.
func (_m *StoreApp) QueryGenres() *StoreGenreQuery {
	return NewStoreAppClient(_m.config).QueryGenres(_m)
}

// QueryImages queries the "images" edge of the StoreApp entity.
func (_m *StoreApp) QueryImages() *ImageQuery {
	return NewStoreAppClient(_m.config).QueryImages(_m)
}

// QueryUserInstallList queries the "user_install_list" edge of the StoreApp entity.
func (_m *StoreApp) QueryUserInstallList() *UserQuery {
	return NewStoreAppClient(_m.config).QueryUserInstallList(_m)
}

// Update returns a builder for updating this StoreApp.
// Note that you need to call StoreApp.Unwrap() before calling this method if this StoreApp
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StoreApp) Update() *StoreAppUpdateOne {
	return NewStoreAppClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StoreApp entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StoreApp) Unwrap() *StoreApp {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entities: StoreApp is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StoreApp) String() string {
	var builder strings.Builder
	builder.WriteString("StoreApp(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	if v := _m.Rating; v != nil {
		builder.WriteString("rating=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reviews=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reviews))
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(_m.Size)
	builder.WriteString(", ")
	builder.WriteString("installs=")
	builder.WriteString(_m.Installs)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("content_rating=")
	builder.WriteString(_m.ContentRating)
	builder.WriteString(", ")
	builder.WriteString("last_updated=")
	builder.WriteString(_m.LastUpdated)
	builder.WriteString(", ")
	builder.WriteString("current_ver=")
	builder.WriteString(_m.CurrentVer)
	builder.WriteString(", ")
	builder.WriteString("in_app_purchases=")
	builder.WriteString(fmt.Sprintf("%v", _m.InAppPurchases))
	builder.WriteString(", ")
	builder.WriteString("ad_supported=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdSupported))
	builder.WriteByte(')')
	return builder.String()
}

// StoreApps is a parsable slice of StoreApp.
type StoreApps []*StoreApp
