// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/storeapp"
	"b3_ux_backend/internal/entities/storegenre"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StoreGenreCreate is the builder for creating a StoreGenre entity.
type StoreGenreCreate struct {
	config
	mutation *StoreGenreMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *StoreGenreCreate) SetName(v string) *StoreGenreCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *StoreGenreCreate) SetID(v uuid.UUID) *StoreGenreCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StoreGenreCreate) SetNillableID(v *uuid.UUID) *StoreGenreCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAppIDs adds the "app" edge to the StoreApp entity by IDs.
func (_c *StoreGenreCreate) AddAppIDs(ids ...uuid.UUID) *StoreGenreCreate {
	_c.mutation.AddAppIDs(ids...)
	return _c
}

// AddApp adds the "app" edges to the StoreApp entity.
func (_c *StoreGenreCreate) AddApp(v ...*StoreApp) *StoreGenreCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAppIDs(ids...)
}

// Mutation returns the StoreGenreMutation object of the builder.
func (_c *StoreGenreCreate) Mutation() *StoreGenreMutation {
	return _c.mutation
}

// Save creates the StoreGenre in the database.
func (_c *StoreGenreCreate) Save(ctx context.Context) (*StoreGenre, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StoreGenreCreate) SaveX(ctx context.Context) *StoreGenre {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreGenreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreGenreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StoreGenreCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := storegenre.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StoreGenreCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`entities: missing required field "StoreGenre.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := storegenre.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entities: validator failed for field "StoreGenre.name": %w`, err)}
		}
	}
	return nil
}

func (_c *StoreGenreCreate) sqlSave(ctx context.Context) (*StoreGenre, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StoreGenreCreate) createSpec() (*StoreGenre, *sqlgraph.CreateSpec) {
	var (
		_node = &StoreGenre{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storegenre.Table, sqlgraph.NewFieldSpec(storegenre.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(storegenre.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   storegenre.AppTable,
			Columns: storegenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storeapp.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StoreGenreCreateBulk is the builder for creating many StoreGenre entities in bulk.
type StoreGenreCreateBulk struct {
	config
	err      error
	builders []*StoreGenreCreate
}

// Save creates the StoreGenre entities in the database.
func (_c *StoreGenreCreateBulk) Save(ctx context.Context) ([]*StoreGenre, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StoreGenre, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreGenreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StoreGenreCreateBulk) SaveX(ctx context.Context) []*StoreGenre {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreGenreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreGenreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
