// Code generated by ent, DO NOT EDIT.

package entities

import (
	"bytes"
	"encoding/json"

	"github.com/olekukonko/errors"

	storeapp "b3_ux_backend/internal/entities/storeapp"

	wywwmovie "b3_ux_backend/internal/entities/wywwmovie"
)

type UpdateField[T any] struct {
	Present bool
	Value   T
}

func (v *UpdateField[T]) UnmarshalJSON(data []byte) error {
	v.Present = true

	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		return errors.New("field cannot be null")
	}

	return json.Unmarshal(data, &v.Value)
}

type StoreAppUpdateOptions struct {
	Name *UpdateField[string] `json:"name" form:"name"`

	Category *UpdateField[storeapp.Category] `json:"category" form:"category"`

	Rating *UpdateField[float32] `json:"rating" form:"rating"`

	Reviews *UpdateField[int32] `json:"reviews" form:"reviews"`

	Size *UpdateField[string] `json:"size" form:"size"`

	Installs *UpdateField[string] `json:"installs" form:"installs"`

	Type *UpdateField[storeapp.Type] `json:"type" form:"type"`

	Price *UpdateField[float32] `json:"price" form:"price"`

	ContentRating *UpdateField[string] `json:"content_rating" form:"content_rating"`

	LastUpdated *UpdateField[string] `json:"last_updated" form:"last_updated"`

	CurrentVer *UpdateField[string] `json:"current_ver" form:"current_ver"`

	InAppPurchases *UpdateField[bool] `json:"in_app_purchases" form:"in_app_purchases"`

	AdSupported *UpdateField[bool] `json:"ad_supported" form:"ad_supported"`
}

func (u *StoreAppUpdate) ApplyUpdateOptions(options *StoreAppUpdateOptions) error {
	if options == nil {
		return errors.New("options cannot be nil")
	}

	if options.Name != nil && options.Name.Present {
		u.SetName(options.Name.Value)
	}

	if options.Category != nil && options.Category.Present {
		u.SetCategory(options.Category.Value)
	}

	if options.Rating != nil && options.Rating.Present {
		u.SetRating(options.Rating.Value)
	}

	if options.Reviews != nil && options.Reviews.Present {
		u.SetReviews(options.Reviews.Value)
	}

	if options.Size != nil && options.Size.Present {
		u.SetSize(options.Size.Value)
	}

	if options.Installs != nil && options.Installs.Present {
		u.SetInstalls(options.Installs.Value)
	}

	if options.Type != nil && options.Type.Present {
		u.SetType(options.Type.Value)
	}

	if options.Price != nil && options.Price.Present {
		u.SetPrice(options.Price.Value)
	}

	if options.ContentRating != nil && options.ContentRating.Present {
		u.SetContentRating(options.ContentRating.Value)
	}

	if options.LastUpdated != nil && options.LastUpdated.Present {
		u.SetLastUpdated(options.LastUpdated.Value)
	}

	if options.CurrentVer != nil && options.CurrentVer.Present {
		u.SetCurrentVer(options.CurrentVer.Value)
	}

	if options.InAppPurchases != nil && options.InAppPurchases.Present {
		u.SetInAppPurchases(options.InAppPurchases.Value)
	}

	if options.AdSupported != nil && options.AdSupported.Present {
		u.SetAdSupported(options.AdSupported.Value)
	}

	return nil
}

type StoreGenreUpdateOptions struct {
	Name *UpdateField[string] `json:"name" form:"name"`
}

func (u *StoreGenreUpdate) ApplyUpdateOptions(options *StoreGenreUpdateOptions) error {
	if options == nil {
		return errors.New("options cannot be nil")
	}

	if options.Name != nil && options.Name.Present {
		u.SetName(options.Name.Value)
	}

	return nil
}

type WywwGenreUpdateOptions struct {
	Name *UpdateField[string] `json:"name" form:"name"`
}

func (u *WywwGenreUpdate) ApplyUpdateOptions(options *WywwGenreUpdateOptions) error {
	if options == nil {
		return errors.New("options cannot be nil")
	}

	if options.Name != nil && options.Name.Present {
		u.SetName(options.Name.Value)
	}

	return nil
}

type WywwMovieUpdateOptions struct {
	MovieTitle *UpdateField[string] `json:"movie_title" form:"movie_title"`

	OriginalTitle *UpdateField[string] `json:"original_title" form:"original_title"`

	ContentRating *UpdateField[wywwmovie.ContentRating] `json:"content_rating" form:"content_rating"`

	Description *UpdateField[string] `json:"description" form:"description"`

	PosterPath *UpdateField[string] `json:"poster_path" form:"poster_path"`

	BannerPath *UpdateField[string] `json:"banner_path" form:"banner_path"`

	ReleasedYear *UpdateField[int32] `json:"released_year" form:"released_year"`

	Runtime *UpdateField[int32] `json:"runtime" form:"runtime"`

	Rating *UpdateField[float32] `json:"rating" form:"rating"`
}

func (u *WywwMovieUpdate) ApplyUpdateOptions(options *WywwMovieUpdateOptions) error {
	if options == nil {
		return errors.New("options cannot be nil")
	}

	if options.MovieTitle != nil && options.MovieTitle.Present {
		u.SetMovieTitle(options.MovieTitle.Value)
	}

	if options.OriginalTitle != nil && options.OriginalTitle.Present {
		u.SetOriginalTitle(options.OriginalTitle.Value)
	}

	if options.ContentRating != nil && options.ContentRating.Present {
		u.SetContentRating(options.ContentRating.Value)
	}

	if options.Description != nil && options.Description.Present {
		u.SetDescription(options.Description.Value)
	}

	if options.PosterPath != nil && options.PosterPath.Present {
		u.SetPosterPath(options.PosterPath.Value)
	}

	if options.BannerPath != nil && options.BannerPath.Present {
		u.SetBannerPath(options.BannerPath.Value)
	}

	if options.ReleasedYear != nil && options.ReleasedYear.Present {
		u.SetReleasedYear(options.ReleasedYear.Value)
	}

	if options.Runtime != nil && options.Runtime.Present {
		u.SetRuntime(options.Runtime.Value)
	}

	if options.Rating != nil && options.Rating.Present {
		u.SetRating(options.Rating.Value)
	}

	return nil
}
