// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/image"
	"b3_ux_backend/internal/entities/storeapp"
	"b3_ux_backend/internal/entities/wywwmovie"
	"time"

	"github.com/google/uuid"
)

type ColorData struct {
	ID uuid.UUID `json:"id"`

	R int `json:"r"`

	G int `json:"g"`

	B int `json:"b"`

	Ratio float32 `json:"ratio"`
}

func (n *Color) ToData() *ColorData {
	result := ColorData{
		ID: n.ID,

		R: n.R,

		G: n.G,

		B: n.B,

		Ratio: n.Ratio,
	}

	return &result
}

type ImageData struct {
	ID uuid.UUID `json:"id"`

	Filename string `json:"filename"`

	Path string `json:"path"`

	Width int `json:"width"`

	Height int `json:"height"`

	Kind image.Kind `json:"kind"`

	Colors []ColorData `json:"colors"`
}

func (n *Image) ToData() *ImageData {
	result := ImageData{
		ID: n.ID,

		Filename: n.Filename,

		Path: n.Path,

		Width: n.Width,

		Height: n.Height,

		Kind: n.Kind,
	}

	if n.Edges.Colors != nil {

		for _, i := range n.Edges.Colors {
			result.Colors = append(result.Colors, *i.ToData())
		}
	}

	return &result
}

type SessionData struct {
	ID uuid.UUID `json:"id"`

	Token string `json:"token"`

	CreatedAt time.Time `json:"created_at"`

	ExpiresAt time.Time `json:"expires_at"`
}

func (n *Session) ToData() *SessionData {
	result := SessionData{
		ID: n.ID,

		Token: n.Token,

		CreatedAt: n.CreatedAt,

		ExpiresAt: n.ExpiresAt,
	}

	return &result
}

type StoreAppData struct {
	ID uuid.UUID `json:"id"`

	Name string `json:"name"`

	Category storeapp.Category `json:"category"`

	Rating *float32 `json:"rating"`

	Reviews int32 `json:"reviews"`

	Size string `json:"size"`

	Installs string `json:"installs"`

	Type storeapp.Type `json:"type"`

	Price float32 `json:"price"`

	ContentRating string `json:"content_rating"`

	LastUpdated string `json:"last_updated"`

	CurrentVer string `json:"current_ver"`

	InAppPurchases bool `json:"in_app_purchases"`

	AdSupported bool `json:"ad_supported"`

	Genres []StoreGenreData `json:"genres"`

	Images []ImageData `json:"images"`
}

func (n *StoreApp) ToData() *StoreAppData {
	result := StoreAppData{
		ID: n.ID,

		Name: n.Name,

		Category: n.Category,

		Rating: n.Rating,

		Reviews: n.Reviews,

		Size: n.Size,

		Installs: n.Installs,

		Type: n.Type,

		Price: n.Price,

		ContentRating: n.ContentRating,

		LastUpdated: n.LastUpdated,

		CurrentVer: n.CurrentVer,

		InAppPurchases: n.InAppPurchases,

		AdSupported: n.AdSupported,
	}

	if n.Edges.Genres != nil {

		for _, i := range n.Edges.Genres {
			result.Genres = append(result.Genres, *i.ToData())
		}
	}

	if n.Edges.Images != nil {

		for _, i := range n.Edges.Images {
			result.Images = append(result.Images, *i.ToData())
		}
	}

	return &result
}

type StoreGenreData struct {
	ID uuid.UUID `json:"id"`

	Name string `json:"name"`
}

func (n *StoreGenre) ToData() *StoreGenreData {
	result := StoreGenreData{
		ID: n.ID,

		Name: n.Name,
	}

	return &result
}

type UserData struct {
	ID uuid.UUID `json:"id"`

	Username string `json:"username"`

	IsAdmin bool `json:"is_admin"`

	Email string `json:"email"`

	Password string `json:"password"`

	RecommendedMovies []WywwMovieData `json:"recommended_movies"`

	WatchedMovies []WywwMovieData `json:"watched_movies"`

	InstalledApps []StoreAppData `json:"installed_apps"`

	Sessions []SessionData `json:"sessions"`
}

func (n *User) ToData() *UserData {
	result := UserData{
		ID: n.ID,

		Username: n.Username,

		IsAdmin: n.IsAdmin,

		Email: n.Email,

		Password: n.Password,
	}

	if n.Edges.RecommendedMovies != nil {

		for _, i := range n.Edges.RecommendedMovies {
			result.RecommendedMovies = append(result.RecommendedMovies, *i.ToData())
		}
	}

	if n.Edges.WatchedMovies != nil {

		for _, i := range n.Edges.WatchedMovies {
			result.WatchedMovies = append(result.WatchedMovies, *i.ToData())
		}
	}

	if n.Edges.InstalledApps != nil {

		for _, i := range n.Edges.InstalledApps {
			result.InstalledApps = append(result.InstalledApps, *i.ToData())
		}
	}

	if n.Edges.Sessions != nil {

		for _, i := range n.Edges.Sessions {
			result.Sessions = append(result.Sessions, *i.ToData())
		}
	}

	return &result
}

type WywwGenreData struct {
	ID uuid.UUID `json:"id"`

	Name string `json:"name"`
}

func (n *WywwGenre) ToData() *WywwGenreData {
	result := WywwGenreData{
		ID: n.ID,

		Name: n.Name,
	}

	return &result
}

type WywwMovieData struct {
	ID uuid.UUID `json:"id"`

	MovieTitle string `json:"movie_title"`

	OriginalTitle string `json:"original_title"`

	ContentRating wywwmovie.ContentRating `json:"content_rating"`

	Description string `json:"description"`

	ReleasedYear int32 `json:"released_year"`

	Runtime int32 `json:"runtime"`

	Rating float32 `json:"rating"`

	Genres []WywwGenreData `json:"genres"`

	Images []ImageData `json:"images"`
}

func (n *WywwMovie) ToData() *WywwMovieData {
	result := WywwMovieData{
		ID: n.ID,

		MovieTitle: n.MovieTitle,

		OriginalTitle: n.OriginalTitle,

		ContentRating: n.ContentRating,

		Description: n.Description,

		ReleasedYear: n.ReleasedYear,

		Runtime: n.Runtime,

		Rating: n.Rating,
	}

	if n.Edges.Genres != nil {

		for _, i := range n.Edges.Genres {
			result.Genres = append(result.Genres, *i.ToData())
		}
	}

	if n.Edges.Images != nil {

		for _, i := range n.Edges.Images {
			result.Images = append(result.Images, *i.ToData())
		}
	}

	return &result
}
