// Code generated by ent, DO NOT EDIT.

package entities

import (
	"encoding/json"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/olekukonko/errors"

	"b3_ux_backend/internal/entities/predicate"

	color "b3_ux_backend/internal/entities/color"

	image "b3_ux_backend/internal/entities/image"

	session "b3_ux_backend/internal/entities/session"

	storeapp "b3_ux_backend/internal/entities/storeapp"

	storegenre "b3_ux_backend/internal/entities/storegenre"

	user "b3_ux_backend/internal/entities/user"

	wywwgenre "b3_ux_backend/internal/entities/wywwgenre"

	wywwmovie "b3_ux_backend/internal/entities/wywwmovie"
)

type FilterOperator string

const (
	EqFilterOperator    FilterOperator = "eq"
	NeFilterOperator    FilterOperator = "ne"
	LtFilterOperator    FilterOperator = "lt"
	LteFilterOperator   FilterOperator = "lte"
	GtFilterOperator    FilterOperator = "gt"
	GteFilterOperator   FilterOperator = "gte"
	InFilterOperator    FilterOperator = "in"
	NotInFilterOperator FilterOperator = "notin"
)

type FilterItem struct {
	Field    string          `json:"field"`
	Operator FilterOperator  `json:"operator"`
	Value    json.RawMessage `json:"value"`
}

func decodeFilterValue[T any](raw json.RawMessage) (T, error) {
	var value T
	err := json.Unmarshal(raw, &value)
	return value, err
}

type FilterPredicate func(*sql.Selector)

func (q *ColorQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("Color", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity Color")
		}
		q.Where(predicate.Color(p))
	}
	return nil
}

func buildColorFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.IDNotIn(value...)), nil
			}

		case "r":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.REQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RGTE(value)), nil

			}

		case "g":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.GGTE(value)), nil

			}

		case "b":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.BGTE(value)), nil

			}

		case "ratio":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(color.RatioGTE(value)), nil

			}

		}
	}

	switch path[0] {

	case "image":
		child, err := buildFilterPredicate("Image", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(color.HasImageWith(
			predicate.Image(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *ImageQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("Image", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity Image")
		}
		q.Where(predicate.Image(p))
	}
	return nil
}

func buildImageFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.IDNotIn(value...)), nil
			}

		case "filename":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.FilenameEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.FilenameNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.FilenameIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.FilenameNotIn(value...)), nil

			}

		case "path":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.PathEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.PathNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.PathIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.PathNotIn(value...)), nil

			}

		case "width":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.WidthGTE(value)), nil

			}

		case "height":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.HeightGTE(value)), nil

			}

		case "kind":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[image.Kind](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.KindEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[image.Kind](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.KindNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]image.Kind](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.KindIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]image.Kind](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(image.KindNotIn(value...)), nil

			}

		}
	}

	switch path[0] {

	case "colors":
		child, err := buildFilterPredicate("Color", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(image.HasColorsWith(
			predicate.Color(child),
		)), nil

	case "movie":
		child, err := buildFilterPredicate("WywwMovie", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(image.HasMovieWith(
			predicate.WywwMovie(child),
		)), nil

	case "store":
		child, err := buildFilterPredicate("StoreApp", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(image.HasStoreWith(
			predicate.StoreApp(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *SessionQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("Session", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity Session")
		}
		q.Where(predicate.Session(p))
	}
	return nil
}

func buildSessionFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.IDNotIn(value...)), nil
			}

		case "token":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.TokenEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.TokenNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.TokenIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.TokenNotIn(value...)), nil

			}

		case "created_at":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.CreatedAtEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.CreatedAtNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.CreatedAtIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.CreatedAtNotIn(value...)), nil

			}

		case "expires_at":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.ExpiresAtEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.ExpiresAtNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.ExpiresAtIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]time.Time](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(session.ExpiresAtNotIn(value...)), nil

			}

		}
	}

	switch path[0] {

	case "artist":
		child, err := buildFilterPredicate("User", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(session.HasArtistWith(
			predicate.User(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *StoreAppQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("StoreApp", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity StoreApp")
		}
		q.Where(predicate.StoreApp(p))
	}
	return nil
}

func buildStoreAppFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.IDNotIn(value...)), nil
			}

		case "name":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.NameEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.NameNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.NameIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.NameNotIn(value...)), nil

			}

		case "category":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[storeapp.Category](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CategoryEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[storeapp.Category](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CategoryNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]storeapp.Category](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CategoryIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]storeapp.Category](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CategoryNotIn(value...)), nil

			}

		case "rating":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.RatingGTE(value)), nil

			}

		case "reviews":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ReviewsGTE(value)), nil

			}

		case "size":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.SizeEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.SizeNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.SizeIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.SizeNotIn(value...)), nil

			}

		case "installs":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.InstallsEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.InstallsNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.InstallsIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.InstallsNotIn(value...)), nil

			}

		case "type":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[storeapp.Type](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.TypeEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[storeapp.Type](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.TypeNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]storeapp.Type](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.TypeIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]storeapp.Type](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.TypeNotIn(value...)), nil

			}

		case "price":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.PriceGTE(value)), nil

			}

		case "content_rating":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ContentRatingEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ContentRatingNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ContentRatingIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.ContentRatingNotIn(value...)), nil

			}

		case "last_updated":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.LastUpdatedEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.LastUpdatedNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.LastUpdatedIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.LastUpdatedNotIn(value...)), nil

			}

		case "current_ver":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CurrentVerEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CurrentVerNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CurrentVerIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.CurrentVerNotIn(value...)), nil

			}

		case "in_app_purchases":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[bool](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.InAppPurchasesEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[bool](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.InAppPurchasesNEQ(value)), nil

			}

		case "ad_supported":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[bool](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.AdSupportedEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[bool](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storeapp.AdSupportedNEQ(value)), nil

			}

		}
	}

	switch path[0] {

	case "genres":
		child, err := buildFilterPredicate("StoreGenre", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(storeapp.HasGenresWith(
			predicate.StoreGenre(child),
		)), nil

	case "images":
		child, err := buildFilterPredicate("Image", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(storeapp.HasImagesWith(
			predicate.Image(child),
		)), nil

	case "user_install_list":
		child, err := buildFilterPredicate("User", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(storeapp.HasUserInstallListWith(
			predicate.User(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *StoreGenreQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("StoreGenre", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity StoreGenre")
		}
		q.Where(predicate.StoreGenre(p))
	}
	return nil
}

func buildStoreGenreFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.IDNotIn(value...)), nil
			}

		case "name":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.NameEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.NameNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.NameIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(storegenre.NameNotIn(value...)), nil

			}

		}
	}

	switch path[0] {

	case "app":
		child, err := buildFilterPredicate("StoreApp", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(storegenre.HasAppWith(
			predicate.StoreApp(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *UserQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("User", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity User")
		}
		q.Where(predicate.User(p))
	}
	return nil
}

func buildUserFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.IDNotIn(value...)), nil
			}

		case "username":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.UsernameEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.UsernameNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.UsernameIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.UsernameNotIn(value...)), nil

			}

		case "is_admin":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[bool](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.IsAdminEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[bool](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.IsAdminNEQ(value)), nil

			}

		case "email":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.EmailEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.EmailNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.EmailIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.EmailNotIn(value...)), nil

			}

		case "password":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.PasswordEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.PasswordNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.PasswordIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(user.PasswordNotIn(value...)), nil

			}

		}
	}

	switch path[0] {

	case "recommended_movies":
		child, err := buildFilterPredicate("WywwMovie", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(user.HasRecommendedMoviesWith(
			predicate.WywwMovie(child),
		)), nil

	case "watched_movies":
		child, err := buildFilterPredicate("WywwMovie", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(user.HasWatchedMoviesWith(
			predicate.WywwMovie(child),
		)), nil

	case "installed_apps":
		child, err := buildFilterPredicate("StoreApp", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(user.HasInstalledAppsWith(
			predicate.StoreApp(child),
		)), nil

	case "sessions":
		child, err := buildFilterPredicate("Session", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(user.HasSessionsWith(
			predicate.Session(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *WywwGenreQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("WywwGenre", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity WywwGenre")
		}
		q.Where(predicate.WywwGenre(p))
	}
	return nil
}

func buildWywwGenreFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.IDNotIn(value...)), nil
			}

		case "name":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.NameEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.NameNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.NameIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwgenre.NameNotIn(value...)), nil

			}

		}
	}

	switch path[0] {

	case "app":
		child, err := buildFilterPredicate("WywwMovie", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(wywwgenre.HasAppWith(
			predicate.WywwMovie(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func (q *WywwMovieQuery) ApplyFilterOptions(filters []FilterItem) error {
	for _, filter := range filters {
		p, err := buildFilterPredicate("WywwMovie", strings.Split(filter.Field, "."), filter.Operator, filter.Value)
		if err != nil {
			return errors.Wrapf(err, "could not build filter predicate for entity WywwMovie")
		}
		q.Where(predicate.WywwMovie(p))
	}
	return nil
}

func buildWywwMovieFilterPredicate(path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	if len(path) == 1 {
		switch path[0] {

		case "id":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.IDEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.IDNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.IDIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]uuid.UUID](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.IDNotIn(value...)), nil
			}

		case "movie_title":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.MovieTitleEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.MovieTitleNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.MovieTitleIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.MovieTitleNotIn(value...)), nil

			}

		case "original_title":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.OriginalTitleEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.OriginalTitleNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.OriginalTitleIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.OriginalTitleNotIn(value...)), nil

			}

		case "content_rating":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[wywwmovie.ContentRating](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ContentRatingEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[wywwmovie.ContentRating](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ContentRatingNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]wywwmovie.ContentRating](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ContentRatingIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]wywwmovie.ContentRating](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ContentRatingNotIn(value...)), nil

			}

		case "description":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.DescriptionEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.DescriptionNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.DescriptionIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]string](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.DescriptionNotIn(value...)), nil

			}

		case "released_year":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.ReleasedYearGTE(value)), nil

			}

		case "runtime":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[int32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RuntimeGTE(value)), nil

			}

		case "rating":
			switch operator {
			case EqFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingEQ(value)), nil

			case NeFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingNEQ(value)), nil

			case InFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingIn(value...)), nil

			case NotInFilterOperator:
				value, err := decodeFilterValue[[]float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingNotIn(value...)), nil

			case LtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingLT(value)), nil

			case LteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingLTE(value)), nil

			case GtFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingGT(value)), nil

			case GteFilterOperator:
				value, err := decodeFilterValue[float32](raw)
				if err != nil {
					return nil, errors.Wrapf(err, "failed to decode filter value for field %s", path[0])
				}

				return FilterPredicate(wywwmovie.RatingGTE(value)), nil

			}

		}
	}

	switch path[0] {

	case "genres":
		child, err := buildFilterPredicate("WywwGenre", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(wywwmovie.HasGenresWith(
			predicate.WywwGenre(child),
		)), nil

	case "images":
		child, err := buildFilterPredicate("Image", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(wywwmovie.HasImagesWith(
			predicate.Image(child),
		)), nil

	case "user_recommendations":
		child, err := buildFilterPredicate("User", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(wywwmovie.HasUserRecommendationsWith(
			predicate.User(child),
		)), nil

	case "user_watchlist":
		child, err := buildFilterPredicate("User", path[1:], operator, raw)
		if err != nil {
			return nil, err
		}

		return FilterPredicate(wywwmovie.HasUserWatchlistWith(
			predicate.User(child),
		)), nil

	}

	return nil, errors.New("could not generate any predicate")
}

func buildFilterPredicate(entity string, path []string, operator FilterOperator, raw json.RawMessage) (FilterPredicate, error) {
	switch entity {

	case "Color":
		return buildColorFilterPredicate(path, operator, raw)

	case "Image":
		return buildImageFilterPredicate(path, operator, raw)

	case "Session":
		return buildSessionFilterPredicate(path, operator, raw)

	case "StoreApp":
		return buildStoreAppFilterPredicate(path, operator, raw)

	case "StoreGenre":
		return buildStoreGenreFilterPredicate(path, operator, raw)

	case "User":
		return buildUserFilterPredicate(path, operator, raw)

	case "WywwGenre":
		return buildWywwGenreFilterPredicate(path, operator, raw)

	case "WywwMovie":
		return buildWywwMovieFilterPredicate(path, operator, raw)

	}

	return nil, errors.New("could not generate any predicate")
}
