// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/predicate"
	"b3_ux_backend/internal/entities/wywwgenre"
	"b3_ux_backend/internal/entities/wywwmovie"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WywwGenreUpdate is the builder for updating WywwGenre entities.
type WywwGenreUpdate struct {
	config
	hooks    []Hook
	mutation *WywwGenreMutation
}

// Where appends a list predicates to the WywwGenreUpdate builder.
func (_u *WywwGenreUpdate) Where(ps ...predicate.WywwGenre) *WywwGenreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WywwGenreUpdate) SetName(v string) *WywwGenreUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WywwGenreUpdate) SetNillableName(v *string) *WywwGenreUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddAppIDs adds the "app" edge to the WywwMovie entity by IDs.
func (_u *WywwGenreUpdate) AddAppIDs(ids ...uuid.UUID) *WywwGenreUpdate {
	_u.mutation.AddAppIDs(ids...)
	return _u
}

// AddApp adds the "app" edges to the WywwMovie entity.
func (_u *WywwGenreUpdate) AddApp(v ...*WywwMovie) *WywwGenreUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAppIDs(ids...)
}

// Mutation returns the WywwGenreMutation object of the builder.
func (_u *WywwGenreUpdate) Mutation() *WywwGenreMutation {
	return _u.mutation
}

// ClearApp clears all "app" edges to the WywwMovie entity.
func (_u *WywwGenreUpdate) ClearApp() *WywwGenreUpdate {
	_u.mutation.ClearApp()
	return _u
}

// RemoveAppIDs removes the "app" edge to WywwMovie entities by IDs.
func (_u *WywwGenreUpdate) RemoveAppIDs(ids ...uuid.UUID) *WywwGenreUpdate {
	_u.mutation.RemoveAppIDs(ids...)
	return _u
}

// RemoveApp removes "app" edges to WywwMovie entities.
func (_u *WywwGenreUpdate) RemoveApp(v ...*WywwMovie) *WywwGenreUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAppIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WywwGenreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WywwGenreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WywwGenreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WywwGenreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WywwGenreUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := wywwgenre.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entities: validator failed for field "WywwGenre.name": %w`, err)}
		}
	}
	return nil
}

func (_u *WywwGenreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wywwgenre.Table, wywwgenre.Columns, sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(wywwgenre.FieldName, field.TypeString, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wywwgenre.AppTable,
			Columns: wywwgenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAppIDs(); len(nodes) > 0 && !_u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wywwgenre.AppTable,
			Columns: wywwgenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wywwgenre.AppTable,
			Columns: wywwgenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wywwgenre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WywwGenreUpdateOne is the builder for updating a single WywwGenre entity.
type WywwGenreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WywwGenreMutation
}

// SetName sets the "name" field.
func (_u *WywwGenreUpdateOne) SetName(v string) *WywwGenreUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WywwGenreUpdateOne) SetNillableName(v *string) *WywwGenreUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddAppIDs adds the "app" edge to the WywwMovie entity by IDs.
func (_u *WywwGenreUpdateOne) AddAppIDs(ids ...uuid.UUID) *WywwGenreUpdateOne {
	_u.mutation.AddAppIDs(ids...)
	return _u
}

// AddApp adds the "app" edges to the WywwMovie entity.
func (_u *WywwGenreUpdateOne) AddApp(v ...*WywwMovie) *WywwGenreUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAppIDs(ids...)
}

// Mutation returns the WywwGenreMutation object of the builder.
func (_u *WywwGenreUpdateOne) Mutation() *WywwGenreMutation {
	return _u.mutation
}

// ClearApp clears all "app" edges to the WywwMovie entity.
func (_u *WywwGenreUpdateOne) ClearApp() *WywwGenreUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// RemoveAppIDs removes the "app" edge to WywwMovie entities by IDs.
func (_u *WywwGenreUpdateOne) RemoveAppIDs(ids ...uuid.UUID) *WywwGenreUpdateOne {
	_u.mutation.RemoveAppIDs(ids...)
	return _u
}

// RemoveApp removes "app" edges to WywwMovie entities.
func (_u *WywwGenreUpdateOne) RemoveApp(v ...*WywwMovie) *WywwGenreUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAppIDs(ids...)
}

// Where appends a list predicates to the WywwGenreUpdate builder.
func (_u *WywwGenreUpdateOne) Where(ps ...predicate.WywwGenre) *WywwGenreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WywwGenreUpdateOne) Select(field string, fields ...string) *WywwGenreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WywwGenre entity.
func (_u *WywwGenreUpdateOne) Save(ctx context.Context) (*WywwGenre, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WywwGenreUpdateOne) SaveX(ctx context.Context) *WywwGenre {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WywwGenreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WywwGenreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WywwGenreUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := wywwgenre.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`entities: validator failed for field "WywwGenre.name": %w`, err)}
		}
	}
	return nil
}

func (_u *WywwGenreUpdateOne) sqlSave(ctx context.Context) (_node *WywwGenre, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wywwgenre.Table, wywwgenre.Columns, sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entities: missing "WywwGenre.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wywwgenre.FieldID)
		for _, f := range fields {
			if !wywwgenre.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entities: invalid field %q for query", f)}
			}
			if f != wywwgenre.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(wywwgenre.FieldName, field.TypeString, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wywwgenre.AppTable,
			Columns: wywwgenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAppIDs(); len(nodes) > 0 && !_u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wywwgenre.AppTable,
			Columns: wywwgenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wywwgenre.AppTable,
			Columns: wywwgenre.AppPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WywwGenre{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wywwgenre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
