// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/predicate"
	"b3_ux_backend/internal/entities/wywwgenre"
	"b3_ux_backend/internal/entities/wywwmovie"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WywwMovieQuery is the builder for querying WywwMovie entities.
type WywwMovieQuery struct {
	config
	ctx        *QueryContext
	order      []wywwmovie.OrderOption
	inters     []Interceptor
	predicates []predicate.WywwMovie
	withGenres *WywwGenreQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WywwMovieQuery builder.
func (_q *WywwMovieQuery) Where(ps ...predicate.WywwMovie) *WywwMovieQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WywwMovieQuery) Limit(limit int) *WywwMovieQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WywwMovieQuery) Offset(offset int) *WywwMovieQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WywwMovieQuery) Unique(unique bool) *WywwMovieQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WywwMovieQuery) Order(o ...wywwmovie.OrderOption) *WywwMovieQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGenres chains the current query on the "genres" edge.
func (_q *WywwMovieQuery) QueryGenres() *WywwGenreQuery {
	query := (&WywwGenreClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wywwmovie.Table, wywwmovie.FieldID, selector),
			sqlgraph.To(wywwgenre.Table, wywwgenre.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, wywwmovie.GenresTable, wywwmovie.GenresPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WywwMovie entity from the query.
// Returns a *NotFoundError when no WywwMovie was found.
func (_q *WywwMovieQuery) First(ctx context.Context) (*WywwMovie, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wywwmovie.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WywwMovieQuery) FirstX(ctx context.Context) *WywwMovie {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WywwMovie ID from the query.
// Returns a *NotFoundError when no WywwMovie ID was found.
func (_q *WywwMovieQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wywwmovie.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WywwMovieQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WywwMovie entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WywwMovie entity is found.
// Returns a *NotFoundError when no WywwMovie entities are found.
func (_q *WywwMovieQuery) Only(ctx context.Context) (*WywwMovie, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wywwmovie.Label}
	default:
		return nil, &NotSingularError{wywwmovie.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WywwMovieQuery) OnlyX(ctx context.Context) *WywwMovie {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WywwMovie ID in the query.
// Returns a *NotSingularError when more than one WywwMovie ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WywwMovieQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wywwmovie.Label}
	default:
		err = &NotSingularError{wywwmovie.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WywwMovieQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WywwMovies.
func (_q *WywwMovieQuery) All(ctx context.Context) ([]*WywwMovie, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WywwMovie, *WywwMovieQuery]()
	return withInterceptors[[]*WywwMovie](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WywwMovieQuery) AllX(ctx context.Context) []*WywwMovie {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WywwMovie IDs.
func (_q *WywwMovieQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(wywwmovie.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WywwMovieQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WywwMovieQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WywwMovieQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WywwMovieQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WywwMovieQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entities: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WywwMovieQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WywwMovieQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WywwMovieQuery) Clone() *WywwMovieQuery {
	if _q == nil {
		return nil
	}
	return &WywwMovieQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]wywwmovie.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.WywwMovie{}, _q.predicates...),
		withGenres: _q.withGenres.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGenres tells the query-builder to eager-load the nodes that are connected to
// the "genres" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WywwMovieQuery) WithGenres(opts ...func(*WywwGenreQuery)) *WywwMovieQuery {
	query := (&WywwGenreClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGenres = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MovieTitle string `json:"movie_title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WywwMovie.Query().
//		GroupBy(wywwmovie.FieldMovieTitle).
//		Aggregate(entities.Count()).
//		Scan(ctx, &v)
func (_q *WywwMovieQuery) GroupBy(field string, fields ...string) *WywwMovieGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WywwMovieGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = wywwmovie.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MovieTitle string `json:"movie_title,omitempty"`
//	}
//
//	client.WywwMovie.Query().
//		Select(wywwmovie.FieldMovieTitle).
//		Scan(ctx, &v)
func (_q *WywwMovieQuery) Select(fields ...string) *WywwMovieSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WywwMovieSelect{WywwMovieQuery: _q}
	sbuild.label = wywwmovie.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WywwMovieSelect configured with the given aggregations.
func (_q *WywwMovieQuery) Aggregate(fns ...AggregateFunc) *WywwMovieSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WywwMovieQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("entities: uninitialized interceptor (forgotten import entities/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !wywwmovie.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entities: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WywwMovieQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WywwMovie, error) {
	var (
		nodes       = []*WywwMovie{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withGenres != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WywwMovie).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WywwMovie{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGenres; query != nil {
		if err := _q.loadGenres(ctx, query, nodes,
			func(n *WywwMovie) { n.Edges.Genres = []*WywwGenre{} },
			func(n *WywwMovie, e *WywwGenre) { n.Edges.Genres = append(n.Edges.Genres, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WywwMovieQuery) loadGenres(ctx context.Context, query *WywwGenreQuery, nodes []*WywwMovie, init func(*WywwMovie), assign func(*WywwMovie, *WywwGenre)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*WywwMovie)
	nids := make(map[uuid.UUID]map[*WywwMovie]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(wywwmovie.GenresTable)
		s.Join(joinT).On(s.C(wywwgenre.FieldID), joinT.C(wywwmovie.GenresPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(wywwmovie.GenresPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(wywwmovie.GenresPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*WywwMovie]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*WywwGenre](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "genres" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *WywwMovieQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WywwMovieQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wywwmovie.Table, wywwmovie.Columns, sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wywwmovie.FieldID)
		for i := range fields {
			if fields[i] != wywwmovie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WywwMovieQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(wywwmovie.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = wywwmovie.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WywwMovieGroupBy is the group-by builder for WywwMovie entities.
type WywwMovieGroupBy struct {
	selector
	build *WywwMovieQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WywwMovieGroupBy) Aggregate(fns ...AggregateFunc) *WywwMovieGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WywwMovieGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WywwMovieQuery, *WywwMovieGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WywwMovieGroupBy) sqlScan(ctx context.Context, root *WywwMovieQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WywwMovieSelect is the builder for selecting fields of WywwMovie entities.
type WywwMovieSelect struct {
	*WywwMovieQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WywwMovieSelect) Aggregate(fns ...AggregateFunc) *WywwMovieSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WywwMovieSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WywwMovieQuery, *WywwMovieSelect](ctx, _s.WywwMovieQuery, _s, _s.inters, v)
}

func (_s *WywwMovieSelect) sqlScan(ctx context.Context, root *WywwMovieQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
