// Code generated by ent, DO NOT EDIT.

package entities

import (
	"b3_ux_backend/internal/entities/predicate"
	"b3_ux_backend/internal/entities/wywwgenre"
	"b3_ux_backend/internal/entities/wywwmovie"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WywwMovieUpdate is the builder for updating WywwMovie entities.
type WywwMovieUpdate struct {
	config
	hooks    []Hook
	mutation *WywwMovieMutation
}

// Where appends a list predicates to the WywwMovieUpdate builder.
func (_u *WywwMovieUpdate) Where(ps ...predicate.WywwMovie) *WywwMovieUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMovieTitle sets the "movie_title" field.
func (_u *WywwMovieUpdate) SetMovieTitle(v string) *WywwMovieUpdate {
	_u.mutation.SetMovieTitle(v)
	return _u
}

// SetNillableMovieTitle sets the "movie_title" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableMovieTitle(v *string) *WywwMovieUpdate {
	if v != nil {
		_u.SetMovieTitle(*v)
	}
	return _u
}

// SetOriginalTitle sets the "original_title" field.
func (_u *WywwMovieUpdate) SetOriginalTitle(v string) *WywwMovieUpdate {
	_u.mutation.SetOriginalTitle(v)
	return _u
}

// SetNillableOriginalTitle sets the "original_title" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableOriginalTitle(v *string) *WywwMovieUpdate {
	if v != nil {
		_u.SetOriginalTitle(*v)
	}
	return _u
}

// SetContentRating sets the "content_rating" field.
func (_u *WywwMovieUpdate) SetContentRating(v wywwmovie.ContentRating) *WywwMovieUpdate {
	_u.mutation.SetContentRating(v)
	return _u
}

// SetNillableContentRating sets the "content_rating" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableContentRating(v *wywwmovie.ContentRating) *WywwMovieUpdate {
	if v != nil {
		_u.SetContentRating(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WywwMovieUpdate) SetDescription(v string) *WywwMovieUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableDescription(v *string) *WywwMovieUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPosterPath sets the "poster_path" field.
func (_u *WywwMovieUpdate) SetPosterPath(v string) *WywwMovieUpdate {
	_u.mutation.SetPosterPath(v)
	return _u
}

// SetNillablePosterPath sets the "poster_path" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillablePosterPath(v *string) *WywwMovieUpdate {
	if v != nil {
		_u.SetPosterPath(*v)
	}
	return _u
}

// SetBannerPath sets the "banner_path" field.
func (_u *WywwMovieUpdate) SetBannerPath(v string) *WywwMovieUpdate {
	_u.mutation.SetBannerPath(v)
	return _u
}

// SetNillableBannerPath sets the "banner_path" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableBannerPath(v *string) *WywwMovieUpdate {
	if v != nil {
		_u.SetBannerPath(*v)
	}
	return _u
}

// SetReleasedYear sets the "released_year" field.
func (_u *WywwMovieUpdate) SetReleasedYear(v int32) *WywwMovieUpdate {
	_u.mutation.ResetReleasedYear()
	_u.mutation.SetReleasedYear(v)
	return _u
}

// SetNillableReleasedYear sets the "released_year" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableReleasedYear(v *int32) *WywwMovieUpdate {
	if v != nil {
		_u.SetReleasedYear(*v)
	}
	return _u
}

// AddReleasedYear adds value to the "released_year" field.
func (_u *WywwMovieUpdate) AddReleasedYear(v int32) *WywwMovieUpdate {
	_u.mutation.AddReleasedYear(v)
	return _u
}

// SetRuntime sets the "runtime" field.
func (_u *WywwMovieUpdate) SetRuntime(v int32) *WywwMovieUpdate {
	_u.mutation.ResetRuntime()
	_u.mutation.SetRuntime(v)
	return _u
}

// SetNillableRuntime sets the "runtime" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableRuntime(v *int32) *WywwMovieUpdate {
	if v != nil {
		_u.SetRuntime(*v)
	}
	return _u
}

// AddRuntime adds value to the "runtime" field.
func (_u *WywwMovieUpdate) AddRuntime(v int32) *WywwMovieUpdate {
	_u.mutation.AddRuntime(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *WywwMovieUpdate) SetRating(v float32) *WywwMovieUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *WywwMovieUpdate) SetNillableRating(v *float32) *WywwMovieUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *WywwMovieUpdate) AddRating(v float32) *WywwMovieUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// AddGenreIDs adds the "genres" edge to the WywwGenre entity by IDs.
func (_u *WywwMovieUpdate) AddGenreIDs(ids ...uuid.UUID) *WywwMovieUpdate {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the WywwGenre entity.
func (_u *WywwMovieUpdate) AddGenres(v ...*WywwGenre) *WywwMovieUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// Mutation returns the WywwMovieMutation object of the builder.
func (_u *WywwMovieUpdate) Mutation() *WywwMovieMutation {
	return _u.mutation
}

// ClearGenres clears all "genres" edges to the WywwGenre entity.
func (_u *WywwMovieUpdate) ClearGenres() *WywwMovieUpdate {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to WywwGenre entities by IDs.
func (_u *WywwMovieUpdate) RemoveGenreIDs(ids ...uuid.UUID) *WywwMovieUpdate {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to WywwGenre entities.
func (_u *WywwMovieUpdate) RemoveGenres(v ...*WywwGenre) *WywwMovieUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WywwMovieUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WywwMovieUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WywwMovieUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WywwMovieUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WywwMovieUpdate) check() error {
	if v, ok := _u.mutation.MovieTitle(); ok {
		if err := wywwmovie.MovieTitleValidator(v); err != nil {
			return &ValidationError{Name: "movie_title", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.movie_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalTitle(); ok {
		if err := wywwmovie.OriginalTitleValidator(v); err != nil {
			return &ValidationError{Name: "original_title", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.original_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentRating(); ok {
		if err := wywwmovie.ContentRatingValidator(v); err != nil {
			return &ValidationError{Name: "content_rating", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.content_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := wywwmovie.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleasedYear(); ok {
		if err := wywwmovie.ReleasedYearValidator(v); err != nil {
			return &ValidationError{Name: "released_year", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.released_year": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Runtime(); ok {
		if err := wywwmovie.RuntimeValidator(v); err != nil {
			return &ValidationError{Name: "runtime", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.runtime": %w`, err)}
		}
	}
	return nil
}

func (_u *WywwMovieUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wywwmovie.Table, wywwmovie.Columns, sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MovieTitle(); ok {
		_spec.SetField(wywwmovie.FieldMovieTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalTitle(); ok {
		_spec.SetField(wywwmovie.FieldOriginalTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentRating(); ok {
		_spec.SetField(wywwmovie.FieldContentRating, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(wywwmovie.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PosterPath(); ok {
		_spec.SetField(wywwmovie.FieldPosterPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.BannerPath(); ok {
		_spec.SetField(wywwmovie.FieldBannerPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleasedYear(); ok {
		_spec.SetField(wywwmovie.FieldReleasedYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedReleasedYear(); ok {
		_spec.AddField(wywwmovie.FieldReleasedYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Runtime(); ok {
		_spec.SetField(wywwmovie.FieldRuntime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRuntime(); ok {
		_spec.AddField(wywwmovie.FieldRuntime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(wywwmovie.FieldRating, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(wywwmovie.FieldRating, field.TypeFloat32, value)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wywwmovie.GenresTable,
			Columns: wywwmovie.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wywwmovie.GenresTable,
			Columns: wywwmovie.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wywwmovie.GenresTable,
			Columns: wywwmovie.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wywwmovie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WywwMovieUpdateOne is the builder for updating a single WywwMovie entity.
type WywwMovieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WywwMovieMutation
}

// SetMovieTitle sets the "movie_title" field.
func (_u *WywwMovieUpdateOne) SetMovieTitle(v string) *WywwMovieUpdateOne {
	_u.mutation.SetMovieTitle(v)
	return _u
}

// SetNillableMovieTitle sets the "movie_title" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableMovieTitle(v *string) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetMovieTitle(*v)
	}
	return _u
}

// SetOriginalTitle sets the "original_title" field.
func (_u *WywwMovieUpdateOne) SetOriginalTitle(v string) *WywwMovieUpdateOne {
	_u.mutation.SetOriginalTitle(v)
	return _u
}

// SetNillableOriginalTitle sets the "original_title" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableOriginalTitle(v *string) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetOriginalTitle(*v)
	}
	return _u
}

// SetContentRating sets the "content_rating" field.
func (_u *WywwMovieUpdateOne) SetContentRating(v wywwmovie.ContentRating) *WywwMovieUpdateOne {
	_u.mutation.SetContentRating(v)
	return _u
}

// SetNillableContentRating sets the "content_rating" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableContentRating(v *wywwmovie.ContentRating) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetContentRating(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WywwMovieUpdateOne) SetDescription(v string) *WywwMovieUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableDescription(v *string) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPosterPath sets the "poster_path" field.
func (_u *WywwMovieUpdateOne) SetPosterPath(v string) *WywwMovieUpdateOne {
	_u.mutation.SetPosterPath(v)
	return _u
}

// SetNillablePosterPath sets the "poster_path" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillablePosterPath(v *string) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetPosterPath(*v)
	}
	return _u
}

// SetBannerPath sets the "banner_path" field.
func (_u *WywwMovieUpdateOne) SetBannerPath(v string) *WywwMovieUpdateOne {
	_u.mutation.SetBannerPath(v)
	return _u
}

// SetNillableBannerPath sets the "banner_path" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableBannerPath(v *string) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetBannerPath(*v)
	}
	return _u
}

// SetReleasedYear sets the "released_year" field.
func (_u *WywwMovieUpdateOne) SetReleasedYear(v int32) *WywwMovieUpdateOne {
	_u.mutation.ResetReleasedYear()
	_u.mutation.SetReleasedYear(v)
	return _u
}

// SetNillableReleasedYear sets the "released_year" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableReleasedYear(v *int32) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetReleasedYear(*v)
	}
	return _u
}

// AddReleasedYear adds value to the "released_year" field.
func (_u *WywwMovieUpdateOne) AddReleasedYear(v int32) *WywwMovieUpdateOne {
	_u.mutation.AddReleasedYear(v)
	return _u
}

// SetRuntime sets the "runtime" field.
func (_u *WywwMovieUpdateOne) SetRuntime(v int32) *WywwMovieUpdateOne {
	_u.mutation.ResetRuntime()
	_u.mutation.SetRuntime(v)
	return _u
}

// SetNillableRuntime sets the "runtime" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableRuntime(v *int32) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetRuntime(*v)
	}
	return _u
}

// AddRuntime adds value to the "runtime" field.
func (_u *WywwMovieUpdateOne) AddRuntime(v int32) *WywwMovieUpdateOne {
	_u.mutation.AddRuntime(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *WywwMovieUpdateOne) SetRating(v float32) *WywwMovieUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *WywwMovieUpdateOne) SetNillableRating(v *float32) *WywwMovieUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *WywwMovieUpdateOne) AddRating(v float32) *WywwMovieUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// AddGenreIDs adds the "genres" edge to the WywwGenre entity by IDs.
func (_u *WywwMovieUpdateOne) AddGenreIDs(ids ...uuid.UUID) *WywwMovieUpdateOne {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the WywwGenre entity.
func (_u *WywwMovieUpdateOne) AddGenres(v ...*WywwGenre) *WywwMovieUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// Mutation returns the WywwMovieMutation object of the builder.
func (_u *WywwMovieUpdateOne) Mutation() *WywwMovieMutation {
	return _u.mutation
}

// ClearGenres clears all "genres" edges to the WywwGenre entity.
func (_u *WywwMovieUpdateOne) ClearGenres() *WywwMovieUpdateOne {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to WywwGenre entities by IDs.
func (_u *WywwMovieUpdateOne) RemoveGenreIDs(ids ...uuid.UUID) *WywwMovieUpdateOne {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to WywwGenre entities.
func (_u *WywwMovieUpdateOne) RemoveGenres(v ...*WywwGenre) *WywwMovieUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// Where appends a list predicates to the WywwMovieUpdate builder.
func (_u *WywwMovieUpdateOne) Where(ps ...predicate.WywwMovie) *WywwMovieUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WywwMovieUpdateOne) Select(field string, fields ...string) *WywwMovieUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WywwMovie entity.
func (_u *WywwMovieUpdateOne) Save(ctx context.Context) (*WywwMovie, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WywwMovieUpdateOne) SaveX(ctx context.Context) *WywwMovie {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WywwMovieUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WywwMovieUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WywwMovieUpdateOne) check() error {
	if v, ok := _u.mutation.MovieTitle(); ok {
		if err := wywwmovie.MovieTitleValidator(v); err != nil {
			return &ValidationError{Name: "movie_title", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.movie_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalTitle(); ok {
		if err := wywwmovie.OriginalTitleValidator(v); err != nil {
			return &ValidationError{Name: "original_title", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.original_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentRating(); ok {
		if err := wywwmovie.ContentRatingValidator(v); err != nil {
			return &ValidationError{Name: "content_rating", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.content_rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := wywwmovie.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleasedYear(); ok {
		if err := wywwmovie.ReleasedYearValidator(v); err != nil {
			return &ValidationError{Name: "released_year", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.released_year": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Runtime(); ok {
		if err := wywwmovie.RuntimeValidator(v); err != nil {
			return &ValidationError{Name: "runtime", err: fmt.Errorf(`entities: validator failed for field "WywwMovie.runtime": %w`, err)}
		}
	}
	return nil
}

func (_u *WywwMovieUpdateOne) sqlSave(ctx context.Context) (_node *WywwMovie, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wywwmovie.Table, wywwmovie.Columns, sqlgraph.NewFieldSpec(wywwmovie.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entities: missing "WywwMovie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wywwmovie.FieldID)
		for _, f := range fields {
			if !wywwmovie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entities: invalid field %q for query", f)}
			}
			if f != wywwmovie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MovieTitle(); ok {
		_spec.SetField(wywwmovie.FieldMovieTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalTitle(); ok {
		_spec.SetField(wywwmovie.FieldOriginalTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentRating(); ok {
		_spec.SetField(wywwmovie.FieldContentRating, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(wywwmovie.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PosterPath(); ok {
		_spec.SetField(wywwmovie.FieldPosterPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.BannerPath(); ok {
		_spec.SetField(wywwmovie.FieldBannerPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleasedYear(); ok {
		_spec.SetField(wywwmovie.FieldReleasedYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedReleasedYear(); ok {
		_spec.AddField(wywwmovie.FieldReleasedYear, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Runtime(); ok {
		_spec.SetField(wywwmovie.FieldRuntime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRuntime(); ok {
		_spec.AddField(wywwmovie.FieldRuntime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(wywwmovie.FieldRating, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(wywwmovie.FieldRating, field.TypeFloat32, value)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wywwmovie.GenresTable,
			Columns: wywwmovie.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wywwmovie.GenresTable,
			Columns: wywwmovie.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wywwmovie.GenresTable,
			Columns: wywwmovie.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wywwgenre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WywwMovie{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wywwmovie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
