// Code generated by ent, DO NOT EDIT.

package wywwmovie

import (
	"b3_ux_backend/internal/entities/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldID, id))
}

// MovieTitle applies equality check predicate on the "movie_title" field. It's identical to MovieTitleEQ.
func MovieTitle(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldMovieTitle, v))
}

// OriginalTitle applies equality check predicate on the "original_title" field. It's identical to OriginalTitleEQ.
func OriginalTitle(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldOriginalTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldDescription, v))
}

// Poster applies equality check predicate on the "poster" field. It's identical to PosterEQ.
func Poster(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldPoster, v))
}

// Thumbnail applies equality check predicate on the "thumbnail" field. It's identical to ThumbnailEQ.
func Thumbnail(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldThumbnail, v))
}

// ReleasedYear applies equality check predicate on the "released_year" field. It's identical to ReleasedYearEQ.
func ReleasedYear(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldReleasedYear, v))
}

// Runtime applies equality check predicate on the "runtime" field. It's identical to RuntimeEQ.
func Runtime(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRuntime, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRating, v))
}

// MovieTitleEQ applies the EQ predicate on the "movie_title" field.
func MovieTitleEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldMovieTitle, v))
}

// MovieTitleNEQ applies the NEQ predicate on the "movie_title" field.
func MovieTitleNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldMovieTitle, v))
}

// MovieTitleIn applies the In predicate on the "movie_title" field.
func MovieTitleIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldMovieTitle, vs...))
}

// MovieTitleNotIn applies the NotIn predicate on the "movie_title" field.
func MovieTitleNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldMovieTitle, vs...))
}

// MovieTitleGT applies the GT predicate on the "movie_title" field.
func MovieTitleGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldMovieTitle, v))
}

// MovieTitleGTE applies the GTE predicate on the "movie_title" field.
func MovieTitleGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldMovieTitle, v))
}

// MovieTitleLT applies the LT predicate on the "movie_title" field.
func MovieTitleLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldMovieTitle, v))
}

// MovieTitleLTE applies the LTE predicate on the "movie_title" field.
func MovieTitleLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldMovieTitle, v))
}

// MovieTitleContains applies the Contains predicate on the "movie_title" field.
func MovieTitleContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldMovieTitle, v))
}

// MovieTitleHasPrefix applies the HasPrefix predicate on the "movie_title" field.
func MovieTitleHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldMovieTitle, v))
}

// MovieTitleHasSuffix applies the HasSuffix predicate on the "movie_title" field.
func MovieTitleHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldMovieTitle, v))
}

// MovieTitleEqualFold applies the EqualFold predicate on the "movie_title" field.
func MovieTitleEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldMovieTitle, v))
}

// MovieTitleContainsFold applies the ContainsFold predicate on the "movie_title" field.
func MovieTitleContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldMovieTitle, v))
}

// OriginalTitleEQ applies the EQ predicate on the "original_title" field.
func OriginalTitleEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldOriginalTitle, v))
}

// OriginalTitleNEQ applies the NEQ predicate on the "original_title" field.
func OriginalTitleNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldOriginalTitle, v))
}

// OriginalTitleIn applies the In predicate on the "original_title" field.
func OriginalTitleIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldOriginalTitle, vs...))
}

// OriginalTitleNotIn applies the NotIn predicate on the "original_title" field.
func OriginalTitleNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldOriginalTitle, vs...))
}

// OriginalTitleGT applies the GT predicate on the "original_title" field.
func OriginalTitleGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldOriginalTitle, v))
}

// OriginalTitleGTE applies the GTE predicate on the "original_title" field.
func OriginalTitleGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldOriginalTitle, v))
}

// OriginalTitleLT applies the LT predicate on the "original_title" field.
func OriginalTitleLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldOriginalTitle, v))
}

// OriginalTitleLTE applies the LTE predicate on the "original_title" field.
func OriginalTitleLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldOriginalTitle, v))
}

// OriginalTitleContains applies the Contains predicate on the "original_title" field.
func OriginalTitleContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldOriginalTitle, v))
}

// OriginalTitleHasPrefix applies the HasPrefix predicate on the "original_title" field.
func OriginalTitleHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldOriginalTitle, v))
}

// OriginalTitleHasSuffix applies the HasSuffix predicate on the "original_title" field.
func OriginalTitleHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldOriginalTitle, v))
}

// OriginalTitleEqualFold applies the EqualFold predicate on the "original_title" field.
func OriginalTitleEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldOriginalTitle, v))
}

// OriginalTitleContainsFold applies the ContainsFold predicate on the "original_title" field.
func OriginalTitleContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldOriginalTitle, v))
}

// ContentRatingEQ applies the EQ predicate on the "content_rating" field.
func ContentRatingEQ(v ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldContentRating, v))
}

// ContentRatingNEQ applies the NEQ predicate on the "content_rating" field.
func ContentRatingNEQ(v ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldContentRating, v))
}

// ContentRatingIn applies the In predicate on the "content_rating" field.
func ContentRatingIn(vs ...ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldContentRating, vs...))
}

// ContentRatingNotIn applies the NotIn predicate on the "content_rating" field.
func ContentRatingNotIn(vs ...ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldContentRating, vs...))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldDescription, v))
}

// PosterEQ applies the EQ predicate on the "poster" field.
func PosterEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldPoster, v))
}

// PosterNEQ applies the NEQ predicate on the "poster" field.
func PosterNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldPoster, v))
}

// PosterIn applies the In predicate on the "poster" field.
func PosterIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldPoster, vs...))
}

// PosterNotIn applies the NotIn predicate on the "poster" field.
func PosterNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldPoster, vs...))
}

// PosterGT applies the GT predicate on the "poster" field.
func PosterGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldPoster, v))
}

// PosterGTE applies the GTE predicate on the "poster" field.
func PosterGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldPoster, v))
}

// PosterLT applies the LT predicate on the "poster" field.
func PosterLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldPoster, v))
}

// PosterLTE applies the LTE predicate on the "poster" field.
func PosterLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldPoster, v))
}

// PosterContains applies the Contains predicate on the "poster" field.
func PosterContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldPoster, v))
}

// PosterHasPrefix applies the HasPrefix predicate on the "poster" field.
func PosterHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldPoster, v))
}

// PosterHasSuffix applies the HasSuffix predicate on the "poster" field.
func PosterHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldPoster, v))
}

// PosterEqualFold applies the EqualFold predicate on the "poster" field.
func PosterEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldPoster, v))
}

// PosterContainsFold applies the ContainsFold predicate on the "poster" field.
func PosterContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldPoster, v))
}

// ThumbnailEQ applies the EQ predicate on the "thumbnail" field.
func ThumbnailEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldThumbnail, v))
}

// ThumbnailNEQ applies the NEQ predicate on the "thumbnail" field.
func ThumbnailNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldThumbnail, v))
}

// ThumbnailIn applies the In predicate on the "thumbnail" field.
func ThumbnailIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldThumbnail, vs...))
}

// ThumbnailNotIn applies the NotIn predicate on the "thumbnail" field.
func ThumbnailNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldThumbnail, vs...))
}

// ThumbnailGT applies the GT predicate on the "thumbnail" field.
func ThumbnailGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldThumbnail, v))
}

// ThumbnailGTE applies the GTE predicate on the "thumbnail" field.
func ThumbnailGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldThumbnail, v))
}

// ThumbnailLT applies the LT predicate on the "thumbnail" field.
func ThumbnailLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldThumbnail, v))
}

// ThumbnailLTE applies the LTE predicate on the "thumbnail" field.
func ThumbnailLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldThumbnail, v))
}

// ThumbnailContains applies the Contains predicate on the "thumbnail" field.
func ThumbnailContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldThumbnail, v))
}

// ThumbnailHasPrefix applies the HasPrefix predicate on the "thumbnail" field.
func ThumbnailHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldThumbnail, v))
}

// ThumbnailHasSuffix applies the HasSuffix predicate on the "thumbnail" field.
func ThumbnailHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldThumbnail, v))
}

// ThumbnailEqualFold applies the EqualFold predicate on the "thumbnail" field.
func ThumbnailEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldThumbnail, v))
}

// ThumbnailContainsFold applies the ContainsFold predicate on the "thumbnail" field.
func ThumbnailContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldThumbnail, v))
}

// ReleasedYearEQ applies the EQ predicate on the "released_year" field.
func ReleasedYearEQ(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldReleasedYear, v))
}

// ReleasedYearNEQ applies the NEQ predicate on the "released_year" field.
func ReleasedYearNEQ(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldReleasedYear, v))
}

// ReleasedYearIn applies the In predicate on the "released_year" field.
func ReleasedYearIn(vs ...int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldReleasedYear, vs...))
}

// ReleasedYearNotIn applies the NotIn predicate on the "released_year" field.
func ReleasedYearNotIn(vs ...int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldReleasedYear, vs...))
}

// ReleasedYearGT applies the GT predicate on the "released_year" field.
func ReleasedYearGT(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldReleasedYear, v))
}

// ReleasedYearGTE applies the GTE predicate on the "released_year" field.
func ReleasedYearGTE(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldReleasedYear, v))
}

// ReleasedYearLT applies the LT predicate on the "released_year" field.
func ReleasedYearLT(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldReleasedYear, v))
}

// ReleasedYearLTE applies the LTE predicate on the "released_year" field.
func ReleasedYearLTE(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldReleasedYear, v))
}

// RuntimeEQ applies the EQ predicate on the "runtime" field.
func RuntimeEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRuntime, v))
}

// RuntimeNEQ applies the NEQ predicate on the "runtime" field.
func RuntimeNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldRuntime, v))
}

// RuntimeIn applies the In predicate on the "runtime" field.
func RuntimeIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldRuntime, vs...))
}

// RuntimeNotIn applies the NotIn predicate on the "runtime" field.
func RuntimeNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldRuntime, vs...))
}

// RuntimeGT applies the GT predicate on the "runtime" field.
func RuntimeGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldRuntime, v))
}

// RuntimeGTE applies the GTE predicate on the "runtime" field.
func RuntimeGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldRuntime, v))
}

// RuntimeLT applies the LT predicate on the "runtime" field.
func RuntimeLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldRuntime, v))
}

// RuntimeLTE applies the LTE predicate on the "runtime" field.
func RuntimeLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldRuntime, v))
}

// RuntimeContains applies the Contains predicate on the "runtime" field.
func RuntimeContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldRuntime, v))
}

// RuntimeHasPrefix applies the HasPrefix predicate on the "runtime" field.
func RuntimeHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldRuntime, v))
}

// RuntimeHasSuffix applies the HasSuffix predicate on the "runtime" field.
func RuntimeHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldRuntime, v))
}

// RuntimeEqualFold applies the EqualFold predicate on the "runtime" field.
func RuntimeEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldRuntime, v))
}

// RuntimeContainsFold applies the ContainsFold predicate on the "runtime" field.
func RuntimeContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldRuntime, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldRating, v))
}

// HasGenres applies the HasEdge predicate on the "genres" edge.
func HasGenres() predicate.WywwMovie {
	return predicate.WywwMovie(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GenresTable, GenresPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenresWith applies the HasEdge predicate on the "genres" edge with a given conditions (other predicates).
func HasGenresWith(preds ...predicate.WywwGenre) predicate.WywwMovie {
	return predicate.WywwMovie(func(s *sql.Selector) {
		step := newGenresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WywwMovie) predicate.WywwMovie {
	return predicate.WywwMovie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WywwMovie) predicate.WywwMovie {
	return predicate.WywwMovie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WywwMovie) predicate.WywwMovie {
	return predicate.WywwMovie(sql.NotPredicates(p))
}
