// Code generated by ent, DO NOT EDIT.

package wywwmovie

import (
	"b3_ux_backend/internal/entities/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldID, id))
}

// MovieTitle applies equality check predicate on the "movie_title" field. It's identical to MovieTitleEQ.
func MovieTitle(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldMovieTitle, v))
}

// OriginalTitle applies equality check predicate on the "original_title" field. It's identical to OriginalTitleEQ.
func OriginalTitle(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldOriginalTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldDescription, v))
}

// PosterPath applies equality check predicate on the "poster_path" field. It's identical to PosterPathEQ.
func PosterPath(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldPosterPath, v))
}

// BannerPath applies equality check predicate on the "banner_path" field. It's identical to BannerPathEQ.
func BannerPath(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldBannerPath, v))
}

// ReleasedYear applies equality check predicate on the "released_year" field. It's identical to ReleasedYearEQ.
func ReleasedYear(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldReleasedYear, v))
}

// Runtime applies equality check predicate on the "runtime" field. It's identical to RuntimeEQ.
func Runtime(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRuntime, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRating, v))
}

// MovieTitleEQ applies the EQ predicate on the "movie_title" field.
func MovieTitleEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldMovieTitle, v))
}

// MovieTitleNEQ applies the NEQ predicate on the "movie_title" field.
func MovieTitleNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldMovieTitle, v))
}

// MovieTitleIn applies the In predicate on the "movie_title" field.
func MovieTitleIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldMovieTitle, vs...))
}

// MovieTitleNotIn applies the NotIn predicate on the "movie_title" field.
func MovieTitleNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldMovieTitle, vs...))
}

// MovieTitleGT applies the GT predicate on the "movie_title" field.
func MovieTitleGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldMovieTitle, v))
}

// MovieTitleGTE applies the GTE predicate on the "movie_title" field.
func MovieTitleGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldMovieTitle, v))
}

// MovieTitleLT applies the LT predicate on the "movie_title" field.
func MovieTitleLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldMovieTitle, v))
}

// MovieTitleLTE applies the LTE predicate on the "movie_title" field.
func MovieTitleLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldMovieTitle, v))
}

// MovieTitleContains applies the Contains predicate on the "movie_title" field.
func MovieTitleContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldMovieTitle, v))
}

// MovieTitleHasPrefix applies the HasPrefix predicate on the "movie_title" field.
func MovieTitleHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldMovieTitle, v))
}

// MovieTitleHasSuffix applies the HasSuffix predicate on the "movie_title" field.
func MovieTitleHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldMovieTitle, v))
}

// MovieTitleEqualFold applies the EqualFold predicate on the "movie_title" field.
func MovieTitleEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldMovieTitle, v))
}

// MovieTitleContainsFold applies the ContainsFold predicate on the "movie_title" field.
func MovieTitleContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldMovieTitle, v))
}

// OriginalTitleEQ applies the EQ predicate on the "original_title" field.
func OriginalTitleEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldOriginalTitle, v))
}

// OriginalTitleNEQ applies the NEQ predicate on the "original_title" field.
func OriginalTitleNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldOriginalTitle, v))
}

// OriginalTitleIn applies the In predicate on the "original_title" field.
func OriginalTitleIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldOriginalTitle, vs...))
}

// OriginalTitleNotIn applies the NotIn predicate on the "original_title" field.
func OriginalTitleNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldOriginalTitle, vs...))
}

// OriginalTitleGT applies the GT predicate on the "original_title" field.
func OriginalTitleGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldOriginalTitle, v))
}

// OriginalTitleGTE applies the GTE predicate on the "original_title" field.
func OriginalTitleGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldOriginalTitle, v))
}

// OriginalTitleLT applies the LT predicate on the "original_title" field.
func OriginalTitleLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldOriginalTitle, v))
}

// OriginalTitleLTE applies the LTE predicate on the "original_title" field.
func OriginalTitleLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldOriginalTitle, v))
}

// OriginalTitleContains applies the Contains predicate on the "original_title" field.
func OriginalTitleContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldOriginalTitle, v))
}

// OriginalTitleHasPrefix applies the HasPrefix predicate on the "original_title" field.
func OriginalTitleHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldOriginalTitle, v))
}

// OriginalTitleHasSuffix applies the HasSuffix predicate on the "original_title" field.
func OriginalTitleHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldOriginalTitle, v))
}

// OriginalTitleEqualFold applies the EqualFold predicate on the "original_title" field.
func OriginalTitleEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldOriginalTitle, v))
}

// OriginalTitleContainsFold applies the ContainsFold predicate on the "original_title" field.
func OriginalTitleContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldOriginalTitle, v))
}

// ContentRatingEQ applies the EQ predicate on the "content_rating" field.
func ContentRatingEQ(v ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldContentRating, v))
}

// ContentRatingNEQ applies the NEQ predicate on the "content_rating" field.
func ContentRatingNEQ(v ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldContentRating, v))
}

// ContentRatingIn applies the In predicate on the "content_rating" field.
func ContentRatingIn(vs ...ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldContentRating, vs...))
}

// ContentRatingNotIn applies the NotIn predicate on the "content_rating" field.
func ContentRatingNotIn(vs ...ContentRating) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldContentRating, vs...))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldDescription, v))
}

// PosterPathEQ applies the EQ predicate on the "poster_path" field.
func PosterPathEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldPosterPath, v))
}

// PosterPathNEQ applies the NEQ predicate on the "poster_path" field.
func PosterPathNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldPosterPath, v))
}

// PosterPathIn applies the In predicate on the "poster_path" field.
func PosterPathIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldPosterPath, vs...))
}

// PosterPathNotIn applies the NotIn predicate on the "poster_path" field.
func PosterPathNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldPosterPath, vs...))
}

// PosterPathGT applies the GT predicate on the "poster_path" field.
func PosterPathGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldPosterPath, v))
}

// PosterPathGTE applies the GTE predicate on the "poster_path" field.
func PosterPathGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldPosterPath, v))
}

// PosterPathLT applies the LT predicate on the "poster_path" field.
func PosterPathLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldPosterPath, v))
}

// PosterPathLTE applies the LTE predicate on the "poster_path" field.
func PosterPathLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldPosterPath, v))
}

// PosterPathContains applies the Contains predicate on the "poster_path" field.
func PosterPathContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldPosterPath, v))
}

// PosterPathHasPrefix applies the HasPrefix predicate on the "poster_path" field.
func PosterPathHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldPosterPath, v))
}

// PosterPathHasSuffix applies the HasSuffix predicate on the "poster_path" field.
func PosterPathHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldPosterPath, v))
}

// PosterPathEqualFold applies the EqualFold predicate on the "poster_path" field.
func PosterPathEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldPosterPath, v))
}

// PosterPathContainsFold applies the ContainsFold predicate on the "poster_path" field.
func PosterPathContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldPosterPath, v))
}

// BannerPathEQ applies the EQ predicate on the "banner_path" field.
func BannerPathEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldBannerPath, v))
}

// BannerPathNEQ applies the NEQ predicate on the "banner_path" field.
func BannerPathNEQ(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldBannerPath, v))
}

// BannerPathIn applies the In predicate on the "banner_path" field.
func BannerPathIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldBannerPath, vs...))
}

// BannerPathNotIn applies the NotIn predicate on the "banner_path" field.
func BannerPathNotIn(vs ...string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldBannerPath, vs...))
}

// BannerPathGT applies the GT predicate on the "banner_path" field.
func BannerPathGT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldBannerPath, v))
}

// BannerPathGTE applies the GTE predicate on the "banner_path" field.
func BannerPathGTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldBannerPath, v))
}

// BannerPathLT applies the LT predicate on the "banner_path" field.
func BannerPathLT(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldBannerPath, v))
}

// BannerPathLTE applies the LTE predicate on the "banner_path" field.
func BannerPathLTE(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldBannerPath, v))
}

// BannerPathContains applies the Contains predicate on the "banner_path" field.
func BannerPathContains(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContains(FieldBannerPath, v))
}

// BannerPathHasPrefix applies the HasPrefix predicate on the "banner_path" field.
func BannerPathHasPrefix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasPrefix(FieldBannerPath, v))
}

// BannerPathHasSuffix applies the HasSuffix predicate on the "banner_path" field.
func BannerPathHasSuffix(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldHasSuffix(FieldBannerPath, v))
}

// BannerPathEqualFold applies the EqualFold predicate on the "banner_path" field.
func BannerPathEqualFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEqualFold(FieldBannerPath, v))
}

// BannerPathContainsFold applies the ContainsFold predicate on the "banner_path" field.
func BannerPathContainsFold(v string) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldContainsFold(FieldBannerPath, v))
}

// ReleasedYearEQ applies the EQ predicate on the "released_year" field.
func ReleasedYearEQ(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldReleasedYear, v))
}

// ReleasedYearNEQ applies the NEQ predicate on the "released_year" field.
func ReleasedYearNEQ(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldReleasedYear, v))
}

// ReleasedYearIn applies the In predicate on the "released_year" field.
func ReleasedYearIn(vs ...int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldReleasedYear, vs...))
}

// ReleasedYearNotIn applies the NotIn predicate on the "released_year" field.
func ReleasedYearNotIn(vs ...int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldReleasedYear, vs...))
}

// ReleasedYearGT applies the GT predicate on the "released_year" field.
func ReleasedYearGT(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldReleasedYear, v))
}

// ReleasedYearGTE applies the GTE predicate on the "released_year" field.
func ReleasedYearGTE(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldReleasedYear, v))
}

// ReleasedYearLT applies the LT predicate on the "released_year" field.
func ReleasedYearLT(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldReleasedYear, v))
}

// ReleasedYearLTE applies the LTE predicate on the "released_year" field.
func ReleasedYearLTE(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldReleasedYear, v))
}

// RuntimeEQ applies the EQ predicate on the "runtime" field.
func RuntimeEQ(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRuntime, v))
}

// RuntimeNEQ applies the NEQ predicate on the "runtime" field.
func RuntimeNEQ(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldRuntime, v))
}

// RuntimeIn applies the In predicate on the "runtime" field.
func RuntimeIn(vs ...int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldRuntime, vs...))
}

// RuntimeNotIn applies the NotIn predicate on the "runtime" field.
func RuntimeNotIn(vs ...int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldRuntime, vs...))
}

// RuntimeGT applies the GT predicate on the "runtime" field.
func RuntimeGT(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldRuntime, v))
}

// RuntimeGTE applies the GTE predicate on the "runtime" field.
func RuntimeGTE(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldRuntime, v))
}

// RuntimeLT applies the LT predicate on the "runtime" field.
func RuntimeLT(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldRuntime, v))
}

// RuntimeLTE applies the LTE predicate on the "runtime" field.
func RuntimeLTE(v int32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldRuntime, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float32) predicate.WywwMovie {
	return predicate.WywwMovie(sql.FieldLTE(FieldRating, v))
}

// HasGenres applies the HasEdge predicate on the "genres" edge.
func HasGenres() predicate.WywwMovie {
	return predicate.WywwMovie(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GenresTable, GenresPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenresWith applies the HasEdge predicate on the "genres" edge with a given conditions (other predicates).
func HasGenresWith(preds ...predicate.WywwGenre) predicate.WywwMovie {
	return predicate.WywwMovie(func(s *sql.Selector) {
		step := newGenresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WywwMovie) predicate.WywwMovie {
	return predicate.WywwMovie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WywwMovie) predicate.WywwMovie {
	return predicate.WywwMovie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WywwMovie) predicate.WywwMovie {
	return predicate.WywwMovie(sql.NotPredicates(p))
}
